"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, Expand, Pause, Play, Volume2, VolumeX, X } from "lucide-react";
import { toast } from "sonner";
import { relationFromCode, type DataMode, type SoRelation, type SyncTemplate } from "@/lib/bluewolf";
import { useWorkspace } from "../app-context";
import { doubleHippodromeLoop, hippodromeLoop, pointOnClosed, svgClosedPath } from "../v09/geometry";
import { fixedVehicleTypes } from "../v09/map";
import { GROUP_COLORS, V10LiveMap, type OverlayKey, type V10GroupKey } from "./map";
import { V10Timeline, type TimelineLayer } from "./timeline";
import { analyzeNavigation } from "./nav-engine";
import { DEFAULT_SO_GROUPING, type SoGroupingSettings } from "./grouping";
import { estimatedWindContribution, windForVehicle, type WindMode } from "./wind";

const overlayLabels: Record<OverlayKey,string>={trace:"עקבה",routes:"נתיבים",hulls:"קבוצות",relations:"יחסים",scoreTrace:"עקבה לפי ציון"};
const layerLabels: Record<TimelineLayer,string>={total:"כולל",sync:"סנכרון",route:"נתיב"};
const tone=(score:number)=>score>=80?"good":score>=50?"medium":"low";
function relations(template:SyncTemplate|undefined):SoRelation[]{return template?.soSpec?.relations?.length?template.soSpec.relations:(template?.values??[]).map(relationFromCode);}
function groupingSettings(settings: unknown):SoGroupingSettings { const s=settings as {soGroupingMaxParallelLegs?:number;soGroupingMaxLateralLegs?:number;soGroupingMaxAngleDeg?:number}; return {maxParallelLegs:s.soGroupingMaxParallelLegs??DEFAULT_SO_GROUPING.maxParallelLegs,maxLateralLegs:s.soGroupingMaxLateralLegs??DEFAULT_SO_GROUPING.maxLateralLegs,maxAngleDeg:s.soGroupingMaxAngleDeg??DEFAULT_SO_GROUPING.maxAngleDeg}; }

function templateMini(template:SyncTemplate,color:string){
  if(template.family==="SI"){const angles=template.values.length?template.values:[120,120];const cumulative=[0];angles.forEach((angle)=>cumulative.push((cumulative.at(-1)??0)+angle));const points=cumulative.map((angle,index)=>{const a=(angle-90)*Math.PI/180,r=index%2?60:86;return{x:180+Math.cos(a)*r,y:120+Math.sin(a)*r};});return <svg viewBox="0 0 360 240" className="v09-dialog-preview"><rect width="360" height="240" rx="18"/><circle cx="180" cy="120" r="86" className="v09-ring"/><circle cx="180" cy="120" r="60" className="v09-ring"/>{points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="9" fill={color}/>)}{angles.map((angle,index)=>{const a=points[index],b=points[index+1];return <g key={index}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="v09-dialog-link"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-5} textAnchor="middle">{angle}°</text></g>;})}</svg>}
  const rel=relations(template);const left=hippodromeLoop({x:80,y:148},22,74,-20),middle=doubleHippodromeLoop({x:180,y:118},20,50,54,26,0),right=hippodromeLoop({x:286,y:148},22,74,20);return <svg viewBox="0 0 360 240" className="v09-dialog-preview"><rect width="360" height="240" rx="18"/><path d={svgClosedPath(left)} stroke={color}/><path d={svgClosedPath(middle)} stroke={color}/><path d={svgClosedPath(right)} stroke={color}/>{[left,middle,right].map((route,index)=>{const p=pointOnClosed(route,index===1?.37:.12);return <g key={index} transform={`translate(${p.x} ${p.y}) rotate(${p.heading})`}><path d="M0-10 6 7 0 4-6 7Z" fill={color}/></g>})}<text x="126" y="46" textAnchor="middle">{rel[0]==="opposite"?"הפוך":rel[0]==="mixed"?"מעורב":"זהה"}</text><text x="250" y="46" textAnchor="middle">{rel[1]==="opposite"?"הפוך":rel[1]==="mixed"?"מעורב":"זהה"}</text></svg>;
}

export function OperatorViewV10({serverId,serverName,dataMode,onInvestigate}:{serverId:string;serverName:string;dataMode:DataMode;onInvestigate:()=>void}){
  const {state,save}=useWorkspace();const vehicleTypes=useMemo(()=>fixedVehicleTypes(state.vehicleTypes),[state.vehicleTypes]);
  const extended=state.settings as typeof state.settings&{trailHistoryMinutes?:number};const trailMinutes=extended.trailHistoryMinutes??30;const groupSettings=useMemo(()=>groupingSettings(state.settings),[state.settings]);
  const [selectedGroup,setSelectedGroup]=useState<V10GroupKey|null>(null);const [selectedVehicle,setSelectedVehicle]=useState<number|null>(null);const [tick,setTick]=useState(80);const [running,setRunning]=useState(true);const [windowMinutes,setWindowMinutes]=useState<30|60|90|120>(30);const [cursor,setCursor]=useState(30);const [layers,setLayers]=useState<TimelineLayer[]>(["total","sync","route"]);const [visibleGroups,setVisibleGroups]=useState<V10GroupKey[]>(["si","so"]);const [overlays,setOverlays]=useState<Record<OverlayKey,boolean>>({trace:true,routes:true,hulls:true,relations:true,scoreTrace:false});const [baseMap,setBaseMap]=useState(state.settings.defaultMap||state.mapServers.find((item)=>item.isDefault)?.id||"engineering");const [dialogOpen,setDialogOpen]=useState(false);const [previewId,setPreviewId]=useState("");const [applyMode,setApplyMode]=useState<"now"|"event-start">("now");const [mutedUntil,setMutedUntil]=useState(0);const [windMode,setWindMode]=useState<WindMode>("gusty");const mapRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setTick((value)=>value+1),1000);return()=>window.clearInterval(timer);},[running]);
  const effectiveWindMode:WindMode=dataMode==="simulation"?windMode:"off";
  const seedScenario=useMemo(()=>analyzeNavigation({serverId,tick,windMode:"off",thresholds:state.thresholds,weights:state.weights,groupingSettings:groupSettings}).scenario,[serverId,tick,state.thresholds,state.weights,groupSettings]);
  const activeTemplate=(key:V10GroupKey)=>{const group=seedScenario.groups[key];const override=state.activeTemplateOverrides[`${serverId}:${group.id}`];return state.templates.find((template)=>template.id===(override??(key==="si"?"tpl-si-120":"tpl-so-chain")))??state.templates.find((template)=>template.family===group.family);};
  const siTemplate=activeTemplate("si"),soTemplate=activeTemplate("so");
  const analysis=useMemo(()=>analyzeNavigation({serverId,tick,windMode:effectiveWindMode,thresholds:state.thresholds,weights:state.weights,siTemplate,soTemplate,groupingSettings:groupSettings}),[serverId,tick,effectiveWindMode,state.thresholds,state.weights,siTemplate,soTemplate,groupSettings]);
  const noWindAnalysis=useMemo(()=>effectiveWindMode==="off"?analysis:analyzeNavigation({serverId,tick,windMode:"off",thresholds:state.thresholds,weights:state.weights,siTemplate,soTemplate,groupingSettings:groupSettings}),[effectiveWindMode,analysis,serverId,tick,state.thresholds,state.weights,siTemplate,soTemplate,groupSettings]);
  const scores={si:analysis.si.score,so:analysis.so.score};const currentGroup=selectedGroup?analysis.scenario.groups[selectedGroup]:null;const currentTemplate=selectedGroup?(selectedGroup==="si"?siTemplate:soTemplate):undefined;const candidateTemplates=currentGroup?state.templates.filter((template)=>template.family===currentGroup.family):[];const preview=candidateTemplates.find((template)=>template.id===previewId)??currentTemplate??candidateTemplates[0];
  const previewScore=selectedGroup&&preview?analyzeNavigation({serverId,tick,windMode:effectiveWindMode,thresholds:state.thresholds,weights:state.weights,siTemplate:selectedGroup==="si"?preview:siTemplate,soTemplate:selectedGroup==="so"?preview:soTemplate,groupingSettings:groupSettings})[selectedGroup].score:null;
  const mapProfiles=state.mapServers.length?state.mapServers:[{id:"engineering",name:"מפת הנדסה",enabled:true}] as never[];
  const toggleLayer=(layer:TimelineLayer)=>setLayers((current)=>current.includes(layer)?(current.length===1?current:current.filter((item)=>item!==layer)):[...current,layer]);const toggleGroup=(group:V10GroupKey)=>setVisibleGroups((current)=>current.includes(group)?(current.length===1?current:current.filter((item)=>item!==group)):[...current,group]);
  const chooseMute=(minutes:number|"restart"|0)=>{if(minutes===0)setMutedUntil(0);else if(minutes==="restart")setMutedUntil(Number.MAX_SAFE_INTEGER);else setMutedUntil(Date.now()+minutes*60_000);};
  const openTemplate=()=>{if(!selectedGroup||!currentTemplate)return;setPreviewId(currentTemplate.id);setDialogOpen(true);};
  const applyTemplate=async()=>{if(!preview||!currentGroup||!selectedGroup)return;const key=`${serverId}:${currentGroup.id}`;await save({...state,activeTemplateOverrides:{...state.activeTemplateOverrides,[key]:preview.id},templateApplications:{...state.templateApplications,[key]:{templateId:preview.id,mode:applyMode,appliedAt:new Date().toISOString()}}},"operator","template-v13",`${currentGroup.id}:${preview.id}:${applyMode}`);setDialogOpen(false);toast.success(`התבנית הוחלה על ${currentGroup.name}`);};

  return <div className="v09-operator v10-operator"><header className="v09-page-head"><div><p className="eyebrow">מפעיל · {dataMode==="simulation"?"סימולציה":"נתוני Influx"}</p><h1>תמונה מבצעית</h1><p>{serverName} · הציונים מחושבים מנתוני הניווט עצמם. רוח היא ראיית הסבר משוערת בלבד.</p></div><div className="v09-actions">{dataMode==="simulation"&&<label className="v10-wind-select">תרחיש רוח<select value={windMode} onChange={(event)=>setWindMode(event.target.value as WindMode)}><option value="off">ללא רוח</option><option value="steady">רוח קבועה</option><option value="gusty">משבים</option><option value="crosswind">רוח צד</option></select></label>}<button onClick={onInvestigate}>מעבר לתחקור</button></div></header>
    <div className="v09-kpis"><article><span>ציון כולל · SI</span><b className={tone(scores.si.total)}>{scores.si.total}</b><small>סנכרון {scores.si.sync} · נתיב {scores.si.route}</small></article><article><span>ציון כולל · SO</span><b className={tone(scores.so.total)}>{scores.so.total}</b><small>סנכרון {scores.so.sync} · נתיב {scores.so.route}</small></article><article><span>אמינות נתונים</span><b>96%</b><small>איחוד והשלמת דגימות</small></article><article><span>שהיה</span><b>4.2s</b><small>יעד מתחת ל־10 שניות</small></article><article><span>רוח משוערת</span><b>{effectiveWindMode==="off"?"ללא":"פעילה"}</b><small>אינה נכנסת ישירות לציון</small></article></div>
    <div className="v09-operator-grid"><section className="v09-panel v09-map-panel"><div className="v09-panel-head"><div><h2>מפה חיה</h2><p>לחיצה על קבוצה פותחת מידע מלא ואפשרות להחלפת תבנית.</p></div><div className="v09-map-select"><label><span>מפת בסיס</span><select value={baseMap} onChange={(event)=>setBaseMap(event.target.value)}>{mapProfiles.filter((item:{enabled?:boolean})=>item.enabled!==false).map((item:{id:string;name:string})=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button aria-label="מסך מלא" onClick={()=>mapRef.current?.requestFullscreen?.()}><Expand/></button></div></div><div className="v09-overlay-bar">{(Object.keys(overlays) as OverlayKey[]).map((key)=><button key={key} className={overlays[key]?"active":""} onClick={()=>setOverlays((current)=>({...current,[key]:!current[key]}))}>{overlayLabels[key]}</button>)}</div><div ref={mapRef} className="v09-map-shell"><V10LiveMap serverId={serverId} tick={tick} baseMap={baseMap} overlays={overlays} vehicleTypes={vehicleTypes} selectedGroup={selectedGroup} selectedVehicle={selectedVehicle} siAngles={siTemplate?.values??[120,120]} soRelations={relations(soTemplate)} trailMinutes={trailMinutes} windMode={effectiveWindMode} thresholds={state.thresholds} weights={state.weights} siTemplate={siTemplate} soTemplate={soTemplate} groupingSettings={groupSettings} onSelectGroup={(group)=>{setSelectedGroup(group);setSelectedVehicle(null);}} onSelectVehicle={(vehicle,group)=>{setSelectedGroup(group);setSelectedVehicle(vehicle);}}/></div></section>
      <aside className="v09-side v10-group-stack">{(["si","so"] as V10GroupKey[]).map((key)=>{const group=analysis.scenario.groups[key],score=analysis[key].score,selected=selectedGroup===key;const windEstimates=group.members.map((member)=>windForVehicle(serverId,tick,member.id,effectiveWindMode));const avgConfidence=windEstimates.length?windEstimates.reduce((s,w)=>s+w.confidence,0)/windEstimates.length:0;const contribution=estimatedWindContribution(score.sync,noWindAnalysis[key].score.sync,avgConfidence);return <article key={key} className={`v09-panel v10-group-card ${selected?"selected":""}`} onClick={()=>{setSelectedGroup(key);setSelectedVehicle(null);}}><div className="v09-group-title"><div><i style={{background:GROUP_COLORS[key]}}/><span><b>{group.name}</b><small>{group.id} · {group.members.length} רכבים</small></span></div><strong className={tone(score.total)}>{score.total}</strong></div><div className="v10-compact-scores"><span>סנכרון<b>{score.sync}</b></span><span>נתיב<b>{score.route}</b></span><span>מיקום יחסי<b>{score.position}</b></span></div>{selected&&<><p className="v09-cause"><b>הסבר תפעולי:</b> {group.reason}. זמן מחזור: שגיאה יחסית {analysis[key].periodErrorPct.toFixed(1)}%; קצב התקדמות: {analysis[key].motionErrorPct.toFixed(1)}%.</p>{key==="so"&&analysis.scenario.groupingNotes?.length?<div className="v10-grouping-evidence"><b>חוקיות קיבוץ</b>{analysis.scenario.groupingNotes.slice(0,3).map((note,index)=><small key={index}>{note}</small>)}</div>:null}<div className="v09-members">{group.members.map((member)=>{const type=vehicleTypes.find((item)=>item.id===member.typeId),wind=windForVehicle(serverId,tick,member.id,effectiveWindMode),evidence=analysis[key].vehicles[member.id];return <button key={member.id} className={selectedVehicle===member.id?"active":""} onClick={(event)=>{event.stopPropagation();setSelectedVehicle(member.id);}}><i style={{background:GROUP_COLORS[key]}}/><span>רכב {member.id}<small>{type?.name??member.typeId} · סטיית נתיב {evidence?.routeDeviation.toFixed(1)??"—"} · רוח משוערת {wind.estimatedKnots} קשר, {wind.estimatedBearingDeg}° מצפון</small></span><b>{evidence?.sync??score.sync}</b></button>})}</div>{effectiveWindMode!=="off"&&<div className="v10-wind-impact"><b>השפעה אפשרית של הרוח · משוערת בלבד</b><span>תרומה משוערת לפגיעה: כ־{contribution.toFixed(1)} נק׳ סנכרון</span><small>מחושב בהשוואה נגדית לאותו ניווט מסומלץ ללא רוח ובשקלול אמינות השערוך. הערך אינו מוזן לחישוב הציון.</small></div>}<button className="primary v10-card-template-button" onClick={(event)=>{event.stopPropagation();openTemplate();}}>החלפת תבנית לקבוצה</button></>}</article>})}
        <article className="v09-panel"><div className="v09-panel-head"><div><h3>התראות למפעיל</h3><p>התראה אינה אירוע עד שהשינוי מאושר לפי חלון היציבות.</p></div><button className="v09-icon-button" onClick={()=>chooseMute(mutedUntil?0:15)}>{mutedUntil?<VolumeX/>:<Volume2/>}</button></div><div className="v09-alert warning"><b>{selectedGroup?analysis.scenario.groups[selectedGroup].name:"תמונת מצב כללית"}</b><span>עודכן עכשיו</span><p>{analysis.scenario.eventNote}</p>{analysis.scenario.ungroupedMembers?.length?<p><b>רכבים שלא קובצו:</b> {analysis.scenario.ungroupedMembers.map((m)=>m.id).join(", ")}. הסיבה היא אי־עמידה בחוקיות הגאומטרית; אין לצרף אותם לציון הקבוצה.</p>:null}</div><div className="v09-mute-choices"><button onClick={()=>chooseMute(5)}>השתק 5 דק׳</button><button onClick={()=>chooseMute(15)}>15 דק׳</button><button onClick={()=>chooseMute(30)}>30 דק׳</button><button onClick={()=>chooseMute("restart")}>עד הפעלה מחדש</button></div></article>
      </aside></div>
    <section className="v09-panel v09-chart-panel"><div className="v09-panel-head"><div><h2>ציר ציונים</h2><p>אותו מנוע ניווט של המפה מחשב כל נקודה בגרף.</p></div><div className="v09-window-picker">{([30,60,90,120] as const).map((value)=><button key={value} className={windowMinutes===value?"active":""} onClick={()=>{setWindowMinutes(value);setCursor(value);}}>{value} דק׳</button>)}</div></div><div className="v09-chart-toggles v10-chart-filters"><div><b>קבוצות</b>{(["si","so"] as V10GroupKey[]).map((group)=><button key={group} style={{borderColor:GROUP_COLORS[group]}} className={visibleGroups.includes(group)?"active":""} onClick={()=>toggleGroup(group)}>{group.toUpperCase()}</button>)}</div><div><b>מדדים</b>{(["total","sync","route"] as TimelineLayer[]).map((layer)=><button key={layer} className={layers.includes(layer)?"active":""} onClick={()=>toggleLayer(layer)}>{layerLabels[layer]}</button>)}</div></div><V10Timeline serverId={serverId} currentTick={tick} windowMinutes={windowMinutes} layers={layers} groups={visibleGroups} cursor={Math.min(cursor,windowMinutes)} onCursor={setCursor} windMode={effectiveWindMode} thresholds={state.thresholds} weights={state.weights} siTemplate={siTemplate} soTemplate={soTemplate} groupingSettings={groupSettings}/></section>
    <section className="v09-panel v09-global-time"><div><button className="v09-icon-button" onClick={()=>setRunning((value)=>!value)}>{running?<Pause/>:<Play/>}</button><b>זמן סימולציה</b><span>t={tick}s</span></div><input type="range" min="0" max="300" value={tick%301} onChange={(event)=>{setRunning(false);setTick(Number(event.target.value));}}/></section>
    {dialogOpen&&selectedGroup&&currentGroup&&<div className="v09-modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)setDialogOpen(false);}}><section className="v09-template-sheet" role="dialog" aria-modal="true" aria-label="החלפת תבנית"><header><div><p className="eyebrow">החלפת תבנית</p><h2>{currentGroup.name}</h2><p>הציון הצפוי מחושב מחדש מאותה סדרת ניווט; הרוח אינה רכיב עצמאי בציון.</p></div><button className="v09-icon-button" onClick={()=>setDialogOpen(false)}><X/></button></header><div className="v09-sheet-scroll"><div className="v09-template-choices">{candidateTemplates.map((template)=><button key={template.id} className={preview?.id===template.id?"active":""} onClick={()=>setPreviewId(template.id)}><b>{template.name}</b><span>{template.constellation}</span></button>)}</div>{preview&&previewScore&&<div className="v09-template-preview-large">{templateMini(preview,GROUP_COLORS[selectedGroup])}<div className="v09-expected"><span>כולל צפוי<b className={tone(previewScore.total)}>{previewScore.total}</b></span><span>סנכרון צפוי<b className={tone(previewScore.sync)}>{previewScore.sync}</b></span><span>נתיב<b>{previewScore.route}</b></span><span>מיקום<b>{previewScore.position}</b></span></div></div>}<div className="v09-mode"><b>ממתי להחיל?</b><button className={applyMode==="now"?"active":""} onClick={()=>setApplyMode("now")}>מעכשיו</button><button className={applyMode==="event-start"?"active":""} onClick={()=>setApplyMode("event-start")}>מתחילת האירוע</button></div></div><footer><button onClick={()=>setDialogOpen(false)}>ביטול</button><button className="primary" onClick={applyTemplate}><Check/>החל תבנית</button></footer></section></div>}
  </div>;
}
