"use client";

import { useEffect,useMemo,useState } from "react";
import { Activity,Clock3,FileChartColumn,HardDrive,Moon,Settings2,Sun,Wifi } from "lucide-react";
import { useTheme } from "next-themes";
import type { DataMode } from "@/lib/bluewolf";
import { CORE_API_VERSION } from "@/lib/algorithm-core-adapter";
import { WorkspaceProvider,useWorkspace } from "./app-context";
import { LoadingScreen } from "./visuals";
import { WolfLogo } from "./wolf-logo";
import { OperatorViewV12 } from "./v12/operator";
import { InvestigationViewV12 } from "./v12/investigation";
import { DeveloperViewV12 } from "./v12/developer";

type MainTab="operator"|"investigation"|"developer";
function AppInner(){const{state,ready,loadProgress,storageMode,revision}=useWorkspace();const{resolvedTheme,setTheme}=useTheme();const[clock,setClock]=useState("--:--:--"),[server,setServer]=useState("1"),[dataMode,setDataMode]=useState<DataMode>("simulation"),[tab,setTab]=useState<MainTab>("operator");useEffect(()=>{const update=()=>setClock(new Intl.DateTimeFormat("he-IL",{timeZone:state.settings.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date()));update();const timer=window.setInterval(update,1000);return()=>window.clearInterval(timer);},[state.settings.timezone]);const serverValue=state.servers.some((item)=>item.id===server&&item.enabled)?server:(state.servers.find((item)=>item.enabled)?.id??"1"),activeServer=useMemo(()=>state.servers.find((item)=>item.id===serverValue)?.name??`שרת ${serverValue}`,[serverValue,state.servers]);if(!ready)return <LoadingScreen progress={loadProgress}/>;return <main className="app-shell v09-shell v10-shell v12-shell"><header className="v09-topbar"><button className="v09-brand" onClick={()=>setTab("operator")}><span className="v09-brand-mark"><WolfLogo/></span><span><b>זאב כחול</b><small>v0.13 · SRS v1.5 · Core {CORE_API_VERSION}</small></span></button><div className="v09-source"><button onClick={()=>setDataMode((value)=>value==="simulation"?"influx":"simulation")}><span className="live-dot"/><span><b>{dataMode==="simulation"?"סימולציית ניווט":"InfluxDB אמיתי"}</b><small>{dataMode==="simulation"?"30 יום היסטוריה דטרמיניסטית":"ללא fallback לסימולטור"}</small></span></button><label><span>שרת</span><select value={serverValue} onChange={(event)=>setServer(event.target.value)}>{state.servers.filter((item)=>item.enabled).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="v09-top-actions"><span className="v09-clock"><Clock3/>{clock}</span><button aria-label="מצב תצוגה" onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")}>{resolvedTheme==="dark"?<Sun/>:<Moon/>}</button></div></header><nav className="v09-main-nav"><button className={tab==="operator"?"active":""} onClick={()=>setTab("operator")}><Activity/>מבצעי</button><button className={tab==="investigation"?"active":""} onClick={()=>setTab("investigation")}><FileChartColumn/>תחקור</button><button className={tab==="developer"?"active":""} onClick={()=>setTab("developer")}><Settings2/>מפתחים</button><div className="v09-nav-status"><span><Wifi/>{activeServer}</span><span><HardDrive/>{storageMode==="cloud"?"מרכזי":"מקומי"}</span><span>Config {revision||1}</span></div></nav>{tab==="operator"&&<OperatorViewV12 key={`op-${serverValue}-${dataMode}`} serverId={serverValue} serverName={activeServer} dataMode={dataMode} onInvestigate={()=>setTab("investigation")}/>} {tab==="investigation"&&<InvestigationViewV12 key={`inv-${serverValue}-${dataMode}`} server={serverValue} dataMode={dataMode} onServerChange={setServer}/>} {tab==="developer"&&<DeveloperViewV12/>}</main>}
export function DashboardAppV12(){return <WorkspaceProvider><AppInner/></WorkspaceProvider>}
