"use client";

import { useMemo, useState } from "react";
import { Download, FileDown, LoaderCircle, Save, Search } from "lucide-react";
import { toast } from "sonner";

import { getServerScenario, relationFromCode, type SavedRoute, type SyncTemplate, type VehicleType } from "@/lib/bluewolf";
import { useWorkspace } from "./app-context";
import { TimelineChartV09, groupLineColor, hippodromeLoop, doubleHippodromeGeometry, type GroupKey, type ScoreLayer } from "./visuals-v09";

type MemberScore = { id:number; total:number; sync:number; route:number; reason:string };
type RootCause = { label:string; sharePct:number; impactPoints:number };
type EventV09 = {
  id:string; start:string; end:string; durationMin:number; family:GroupKey; group:string; templateId:string;
  total:number; sync:number; route:number; members:MemberScore[]; rootCauses:RootCause[];
  startReason:string; endReason:string; joinedVehicle?:number; leftVehicle?:number; routeNames:string[];
};
type EventEdit = { note:string; templateId:string; arena?:string };
type EffectiveEvent = EventV09 & { effectiveTotal:number; effectiveSync:number; effectiveRoute:number; templateName:string; note:string };

type Point={x:number;y:number};
const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
const memberOffsets=[4,-7,2,-11,1,-4];

function routeNamesFor(family:GroupKey,routes:SavedRoute[]){const wanted=family.toUpperCase();const names=routes.filter(r=>r.family===wanted).map(r=>r.name);return names.length?names:[family==="si"?"SI detected route":"SO detected route"];}

function buildEvents(serverId:string,routes:SavedRoute[]):EventV09[]{
  const scenario=getServerScenario(serverId),si=scenario.groups.si,so=scenario.groups.so;
  const members=(family:GroupKey,total:number,sync:number,route:number)=>scenario.groups[family].members.map((m,index)=>({id:m.id,total:clamp(total+memberOffsets[index%memberOffsets.length]),sync:clamp(sync+memberOffsets[(index+1)%memberOffsets.length]),route:clamp(route+memberOffsets[(index+2)%memberOffsets.length]),reason:family==="si"?(index===1?"סטיית זווית יחסית":"פאזה ומשיק יציבים"):(index===3?"איחור בפנייה":"פאזה לאורך השרשרת")}));
  const soMembers=so.members.map(m=>m.id),siMembers=si.members.map(m=>m.id);
  return [
    {id:`${serverId}-event-01`,start:"17:08",end:"17:42",durationMin:34,family:"si",group:si.id,templateId:si.templateId,total:Math.max(72,si.total-4),sync:Math.max(70,si.sync-5),route:Math.max(70,si.route-2),members:members("si",Math.max(72,si.total-4),Math.max(70,si.sync-5),Math.max(70,si.route-2)),rootCauses:[{label:"סטיית זווית בין רכבים",sharePct:18,impactPoints:7.4},{label:"סטייה קלה מהמשיק",sharePct:9,impactPoints:3.2}],startReason:`הקבוצה אושרה לאחר חלון היציבות; רכב ${siMembers[0]} הצטרף והשלים את הקבוצה`,endReason:`רכב ${siMembers.at(-1)} עזב; שינוי החברות נשמר מעבר ל־hold`,joinedVehicle:siMembers[0],leftVehicle:siMembers.at(-1),routeNames:routeNamesFor("si",routes)},
    {id:`${serverId}-event-02`,start:"17:48",end:"18:39",durationMin:51,family:"so",group:so.id,templateId:so.templateId,total:so.total,sync:so.sync,route:so.route,members:members("so",so.total,so.sync,so.route),rootCauses:[{label:"איחור בתזמון פנייה",sharePct:31,impactPoints:17.6},{label:"פער פאזה באזור פנייה",sharePct:22,impactPoints:10.4},{label:"סטיית מרחק מהנתיב",sharePct:8,impactPoints:4.1}],startReason:`רכב ${soMembers[0]} הצטרף ו־SO chain אושרה עם חברות יציבה`,endReason:`רכב ${soMembers.at(-1)} יצא; גבול Event נוצר לאחר hold`,joinedVehicle:soMembers[0],leftVehicle:soMembers.at(-1),routeNames:routeNamesFor("so",routes)},
    {id:`${serverId}-event-03`,start:"18:44",end:"19:26",durationMin:42,family:"si",group:si.id,templateId:si.templateId,total:Math.min(95,si.total+5),sync:Math.min(97,si.sync+4),route:Math.min(94,si.route+6),members:members("si",Math.min(95,si.total+5),Math.min(97,si.sync+4),Math.min(94,si.route+6)),rootCauses:[{label:"סטיית משיק קלה",sharePct:6,impactPoints:2.1},{label:"פער מחזור קצר",sharePct:4,impactPoints:1.7}],startReason:`רכב ${siMembers.at(-1)} חזר; קבוצת SI התקבעה מחדש`,endReason:"סיום טווח התחקור",joinedVehicle:siMembers.at(-1),routeNames:routeNamesFor("si",routes)},
  ];
}

function templateRecalc(event:EventV09,original:SyncTemplate|undefined,selected:SyncTemplate|undefined,thresholds:ReturnType<typeof useWorkspace>["state"]["thresholds"]){
  if(!selected||selected.id===original?.id)return{total:event.total,sync:event.sync,route:event.route};
  const base=original?.values??[];
  let position=100;
  if(event.family==="si"){
    const scores=selected.values.map((value,index)=>{const error=Math.abs(value-(base[index]??value));if(error<=thresholds.siPositionFullDeg)return 100;if(error>=thresholds.siPositionZeroDeg)return 0;return 100*(thresholds.siPositionZeroDeg-error)/Math.max(1,thresholds.siPositionZeroDeg-thresholds.siPositionFullDeg);});position=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:100;
  }else{
    const active=base.map(relationFromCode),preview=selected.values.map(relationFromCode);const scores=preview.map((r,i)=>r===(active[i]??r)?100:(r==="mixed"||active[i]==="mixed")?35:0);position=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:100;
  }
  const sync=clamp(position*.6+clamp(event.sync+8)*.2+clamp(event.sync+5)*.2),route=event.route,total=clamp(sync*.75+route*.25);return{total,sync,route};
}

function pdfText(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,size=26,weight=500,color="#17313d"){ctx.fillStyle=color;ctx.font=`${weight} ${size}px Arial, sans-serif`;ctx.textAlign="right";ctx.direction="rtl";ctx.fillText(text,x,y);}
function page(){const canvas=document.createElement("canvas");canvas.width=1240;canvas.height=1754;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");ctx.fillStyle="#f5f9fb";ctx.fillRect(0,0,1240,1754);return{canvas,ctx};}
function drawPolyline(ctx:CanvasRenderingContext2D,points:Point[],color:string,width:number,offsetX:number,offsetY:number,scale:number,close=true){if(!points.length)return;ctx.beginPath();ctx.moveTo(offsetX+points[0].x*scale,offsetY+points[0].y*scale);for(const p of points.slice(1))ctx.lineTo(offsetX+p.x*scale,offsetY+p.y*scale);if(close)ctx.closePath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function drawReportMap(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,event:EffectiveEvent|null,eventIndex=0){
  ctx.save();ctx.fillStyle="#e9f1f6";ctx.fillRect(x,y,w,h);ctx.strokeStyle="rgba(70,105,135,.12)";ctx.lineWidth=1;for(let gx=x;gx<x+w;gx+=42){ctx.beginPath();ctx.moveTo(gx,y);ctx.lineTo(gx,y+h);ctx.stroke();}for(let gy=y;gy<y+h;gy+=42){ctx.beginPath();ctx.moveTo(x,gy);ctx.lineTo(x+w,gy);ctx.stroke();}
  ctx.strokeStyle="rgba(74,108,138,.18)";ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(x+20,y+h*.80);ctx.bezierCurveTo(x+w*.22,y+h*.62,x+w*.35,y+h*.9,x+w*.53,y+h*.60);ctx.bezierCurveTo(x+w*.72,y+h*.34,x+w*.84,y+h*.56,x+w-20,y+h*.43);ctx.stroke();
  const sx=w/1000,sy=h/500,s=Math.min(sx,sy);const ox=x+(w-1000*s)/2,oy=y+(h-500*s)/2;
  const circle=(cx:number,cy:number,r:number,color:string)=>{ctx.beginPath();ctx.arc(ox+cx*s,oy+cy*s,r*s,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=5;ctx.stroke();};
  circle(220,250,105,"#ff9f43");circle(220,250,72,"#34b7eb");circle(220,250,44,"#9068ff");
  const left=hippodromeLoop({x:500,y:360},95,29,-38);const dbl=doubleHippodromeGeometry({x:730,y:250},.64,-6);const right=hippodromeLoop({x:915,y:145},75,26,52);
  drawPolyline(ctx,left,"#ff9f43",5,ox,oy,s);drawPolyline(ctx,dbl.left,"#34b7eb",5,ox,oy,s);drawPolyline(ctx,dbl.right,"#34b7eb",5,ox,oy,s);drawPolyline(ctx,dbl.connector,"#34b7eb",5,ox,oy,s,false);drawPolyline(ctx,right,"#9068ff",5,ox,oy,s);
  const traceColor=event?groupLineColor[event.family]:"#1bb19f";ctx.fillStyle=traceColor;const phases=Array.from({length:22},(_,i)=>i/22);const traceLoop=event?.family==="si"?Array.from({length:120},(_,i)=>({x:220+Math.cos(i/120*Math.PI*2)*105,y:250+Math.sin(i/120*Math.PI*2)*105})):dbl.left;phases.forEach((phase,i)=>{const idx=Math.floor(phase*(traceLoop.length-1));const p=traceLoop[idx];ctx.globalAlpha=.45+i/45;ctx.beginPath();ctx.arc(ox+(p.x+(eventIndex*4))*s,oy+(p.y+(eventIndex*2))*s,4,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;
  if(event){ctx.fillStyle=traceColor;ctx.beginPath();ctx.arc(ox+(event.family==="si"?220:730)*s,oy+(event.family==="si"?250:250)*s,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="700 16px Arial";ctx.fillText(`E${eventIndex+1}`,ox+(event.family==="si"?220:730)*s,oy+(event.family==="si"?256:256)*s);}
  ctx.restore();
}
function summaryPage(server:string,from:string,to:string,events:EffectiveEvent[],weighted:number){const{canvas,ctx}=page();const g=ctx.createLinearGradient(70,70,1170,330);g.addColorStop(0,"#071c38");g.addColorStop(.6,"#0c7087");g.addColorStop(1,"#20b8a6");ctx.fillStyle=g;ctx.fillRect(70,70,1100,285);pdfText(ctx,"זאב כחול · דוח תחקור",1110,160,52,800,"#fff");pdfText(ctx,`שרת ${server} · ${from.replace("T"," ")} — ${to.replace("T"," ")}`,1110,220,24,500,"#dff6f4");pdfText(ctx,`ציון משוקלל ${weighted} · ${events.length} אירועים`,1110,295,30,700,"#fff");pdfText(ctx,"מפת סיכום כל האירועים",1110,435,30,800);drawReportMap(ctx,70,475,1100,510,null);events.forEach((event,index)=>{pdfText(ctx,`E${index+1} · ${event.group} · ${event.start}–${event.end} · ${event.effectiveTotal}`,1110,1050+index*100,24,700,groupLineColor[event.family]);pdfText(ctx,event.endReason,1110,1083+index*100,18,500,"#617783");});return canvas;}
function eventPage(event:EffectiveEvent,index:number){const{canvas,ctx}=page();ctx.fillStyle=groupLineColor[event.family];ctx.fillRect(70,70,1100,190);pdfText(ctx,`E${index+1} · ${event.group}`,1110,145,44,800,"#fff");pdfText(ctx,`${event.start}–${event.end} · ${event.durationMin} דק׳ · ${event.templateName}`,1110,202,23,500,"#eefaff");pdfText(ctx,`כולל ${event.effectiveTotal} · Sync ${event.effectiveSync} · Route ${event.effectiveRoute}`,1110,335,29,800);pdfText(ctx,"מפת האירוע",1110,425,28,800);drawReportMap(ctx,70,460,1100,455,event,index);pdfText(ctx,"התחלה",1110,990,24,800);pdfText(ctx,event.startReason,1110,1030,20,500,"#556d77");pdfText(ctx,"סיום",1110,1100,24,800);pdfText(ctx,event.endReason,1110,1140,20,500,"#556d77");pdfText(ctx,"רכבים",1110,1225,26,800);event.members.slice(0,5).forEach((m,row)=>pdfText(ctx,`${m.id}   כולל ${m.total}   Sync ${m.sync}   Route ${m.route}   ${m.reason}`,1110,1270+row*55,19,600));pdfText(ctx,"גורמי שורש",1110,1570,25,800);event.rootCauses.slice(0,3).forEach((c,row)=>pdfText(ctx,`${c.label} · ${c.sharePct}% זמן · השפעה −${c.impactPoints}`,1110,1610+row*40,18,500,"#607781"));return canvas;}
function jpeg(canvas:HTMLCanvasElement){const raw=atob(canvas.toDataURL("image/jpeg",.92).split(",")[1]);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function concat(parts:Uint8Array[]){const n=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
function pdfFromCanvases(canvases:HTMLCanvasElement[]){const enc=new TextEncoder(),images=canvases.map(jpeg),objectCount=2+images.length*3,bodies:Uint8Array[]=Array.from({length:objectCount+1},()=>new Uint8Array()),pageIds=images.map((_,i)=>3+i*3);bodies[1]=enc.encode("<< /Type /Catalog /Pages 2 0 R >>");bodies[2]=enc.encode(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${images.length} >>`);images.forEach((image,index)=>{const pageId=3+index*3,contentId=pageId+1,imageId=pageId+2,content=enc.encode("q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n");bodies[pageId]=enc.encode(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);bodies[contentId]=concat([enc.encode(`<< /Length ${content.length} >>\nstream\n`),content,enc.encode("endstream")]);bodies[imageId]=concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`),image,enc.encode("\nendstream")]);});const parts=[enc.encode("%PDF-1.4\n")],offsets=Array(objectCount+1).fill(0);let length=parts[0].length;for(let id=1;id<=objectCount;id++){offsets[id]=length;const obj=concat([enc.encode(`${id} 0 obj\n`),bodies[id],enc.encode("\nendobj\n")]);parts.push(obj);length+=obj.length;}const xref=length;let table=`xref\n0 ${objectCount+1}\n0000000000 65535 f \n`;for(let id=1;id<=objectCount;id++)table+=`${String(offsets[id]).padStart(10,"0")} 00000 n \n`;table+=`trailer\n<< /Size ${objectCount+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc.encode(table));return concat(parts);}
function downloadPdf(server:string,from:string,to:string,events:EffectiveEvent[],weighted:number){const canvases=[summaryPage(server,from,to,events,weighted),...events.map(eventPage)],bytes=pdfFromCanvases(canvases),blob=new Blob([bytes],{type:"application/pdf"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`blue-wolf-v09-${server}-${from.slice(0,10)}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}

function SummaryMap({events}: {events:EffectiveEvent[]}){return <svg className="v09-retro-map" viewBox="0 0 1000 470"><defs><pattern id="v09-retro-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40"/></pattern></defs><rect width="1000" height="470"/><rect width="1000" height="470" fill="url(#v09-retro-grid)"/><circle cx="220" cy="235" r="105" stroke="#ff9f43" fill="none" strokeWidth="5"/><circle cx="220" cy="235" r="72" stroke="#34b7eb" fill="none" strokeWidth="5"/><circle cx="220" cy="235" r="44" stroke="#9068ff" fill="none" strokeWidth="5"/><path d="M445 355 C430 313 451 273 490 260 L565 235 C605 222 645 241 657 279 C669 318 648 355 610 368 L535 393 C495 406 457 393 445 355Z" stroke="#ff9f43" fill="none" strokeWidth="5"/><path d="M650 225 C635 181 659 142 700 130 L774 108 C814 96 852 118 863 157 C874 196 851 233 812 244 L738 266 C697 278 662 264 650 225Z" stroke="#34b7eb" fill="none" strokeWidth="5"/><path d="M790 370 C775 330 796 291 835 279 L900 258 C938 246 970 267 978 303" stroke="#9068ff" fill="none" strokeWidth="5"/>{events.map((event,index)=><g key={event.id} transform={`translate(${event.family==="si"?220:690+index*55} ${event.family==="si"?235:250-index*38})`}><circle r="16" fill={groupLineColor[event.family]}/><text textAnchor="middle" y="5">E{index+1}</text></g>)}</svg>}

export function InvestigationViewV09({server,onServerChange}:{server:string;onServerChange:(server:string)=>void}){
  const {state,save}=useWorkspace();const [from,setFrom]=useState("2026-09-02T17:00"),[to,setTo]=useState("2026-09-02T19:30"),[loading,setLoading]=useState(false),[familyFilter,setFamilyFilter]=useState<"all"|GroupKey>("all"),[selectedId,setSelectedId]=useState(`${server}-event-02`),[cursor,setCursor]=useState(119),[layers,setLayers]=useState<ScoreLayer[]>(["total","sync","route"]),[edits,setEdits]=useState<Record<string,EventEdit>>(()=>structuredClone(state.investigationEdits));
  const allEvents=useMemo(()=>buildEvents(server,state.routes),[server,state.routes]);const events=allEvents.filter(e=>familyFilter==="all"||e.family===familyFilter);const selectedBase=allEvents.find(e=>e.id===selectedId)??allEvents[0];const edit=edits[selectedBase.id]??state.investigationEdits[selectedBase.id]??{note:"",templateId:selectedBase.templateId};const effective:EffectiveEvent[]=allEvents.map(event=>{const e=edits[event.id]??state.investigationEdits[event.id]??{note:"",templateId:event.templateId};const base=state.templates.find(t=>t.id===event.templateId),template=state.templates.find(t=>t.id===e.templateId)??base,result=templateRecalc(event,base,template,state.thresholds);return{...event,effectiveTotal:result.total,effectiveSync:result.sync,effectiveRoute:result.route,templateName:template?.name??"ללא תבנית",note:e.note};});const totalMin=effective.reduce((s,e)=>s+e.durationMin,0),weighted=Math.round(effective.reduce((s,e)=>s+e.effectiveTotal*e.durationMin,0)/Math.max(1,totalMin)),best=[...effective].sort((a,b)=>b.effectiveTotal-a.effectiveTotal)[0],selectedEffective=effective.find(e=>e.id===selectedBase.id)??effective[0];
  const updateEdit=(patch:Partial<EventEdit>)=>setEdits(current=>({...current,[selectedBase.id]:{...edit,...patch}}));const saveEdit=async()=>{const next={...state.investigationEdits,[selectedBase.id]:{...edit,note:edit.note.trim()}};await save({...state,investigationEdits:next},"investigation","event-edit-v09",selectedBase.id);toast.success("התיקון נשמר והציון חושב מחדש");};
  const toggle=(layer:ScoreLayer)=>setLayers(current=>current.includes(layer)?(current.length===1?current:current.filter(x=>x!==layer)):[...current,layer]);
  return <div className="v09-investigation"><section className="glass-panel v09-investigation-filter"><div><p className="eyebrow">AFTER ACTION</p><h2>תחקור לאחור</h2><p>Start/Stop מציינים גם איזה רכב הצטרף או עזב.</p></div><div className="v09-form-grid"><label>שרת<select value={server} onChange={e=>{onServerChange(e.target.value);setSelectedId(`${e.target.value}-event-02`);}}>{state.servers.filter(s=>s.enabled).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>מתאריך<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>עד תאריך<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="v09-btn primary" onClick={()=>{if(new Date(from)>=new Date(to)){toast.error("טווח זמן לא חוקי");return;}setLoading(true);setTimeout(()=>{setLoading(false);toast.success("הטווח נטען");},550);}}>{loading?<LoaderCircle className="spin"/>:<Search/>}{loading?"טוען":"טען"}</button></div></section><div className="v09-report-kpis"><article className="glass-panel"><span>אירועים</span><b>{effective.length}</b><small>{totalMin} דקות</small></article><article className="glass-panel"><span>ציון משוקלל</span><b>{weighted}</b><small>לפי משך Event</small></article><article className="glass-panel"><span>Best Event</span><b>{best.effectiveTotal}</b><small>{best.start}–{best.end}</small></article><article className="glass-panel"><span>מפות PDF</span><b>✓</b><small>Summary + כל Event</small></article></div>
    <section className="glass-panel v09-summary-map"><header><div><h3>מפת סיכום כל האירועים</h3><p>נתיבים בצבע סוג רכב; Events בצבע קבוצה.</p></div><div><button className="v09-btn secondary" onClick={()=>{const blob=new Blob([JSON.stringify({server,from,to,weighted,events:effective},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="bluewolf-v09.json";a.click();URL.revokeObjectURL(url);}}><Download/>JSON</button><button className="v09-btn primary" onClick={()=>{try{downloadPdf(server,from,to,effective,weighted);toast.success("PDF נוצר עם מפות Summary ו־Event");}catch(e){toast.error(`PDF נכשל: ${e instanceof Error?e.message:"unknown"}`);}}><FileDown/>PDF עם מפות</button></div></header><SummaryMap events={effective}/></section>
    <section className="glass-panel v09-report-timeline"><header><div><h3>ציונים לאורך הטווח</h3><p>SI + SO יחד; אפשר להסתיר Total/Sync/Route.</p></div><div className="v09-layer-legend">{(["total","sync","route"] as ScoreLayer[]).map(layer=><button key={layer} className={layers.includes(layer)?"active":""} onClick={()=>toggle(layer)}>{layer}</button>)}</div></header><TimelineChartV09 serverId={server} windowMinutes={120} layers={layers} cursor={cursor} onCursor={setCursor}/></section>
    <div className="v09-report-layout"><aside className="glass-panel v09-event-list"><div className="v09-family-filter"><button className={familyFilter==="all"?"active":""} onClick={()=>setFamilyFilter("all")}>הכל</button><button className={familyFilter==="si"?"active":""} onClick={()=>setFamilyFilter("si")}>SI</button><button className={familyFilter==="so"?"active":""} onClick={()=>setFamilyFilter("so")}>SO</button></div>{events.map((event,index)=><button key={event.id} className={selectedBase.id===event.id?"active":""} onClick={()=>setSelectedId(event.id)}><span style={{background:groupLineColor[event.family]}}>E{allEvents.indexOf(event)+1}</span><div><b>{event.group}</b><small>{event.start}–{event.end}</small><em>{event.startReason}</em></div><strong>{effective.find(e=>e.id===event.id)?.effectiveTotal}</strong></button>)}</aside><main className="glass-panel v09-event-detail"><header><div><p className="eyebrow">{selectedEffective.family.toUpperCase()} · {selectedEffective.id}</p><h2>{selectedEffective.group}</h2><p>{selectedEffective.start}–{selectedEffective.end} · {selectedEffective.durationMin} דק׳</p></div><b className="v09-big-score">{selectedEffective.effectiveTotal}</b></header><div className="v09-event-reasons"><article><span>התחלה</span><b>{selectedEffective.startReason}</b>{selectedEffective.joinedVehicle&&<small>רכב מצטרף: {selectedEffective.joinedVehicle}</small>}</article><article><span>סיום</span><b>{selectedEffective.endReason}</b>{selectedEffective.leftVehicle&&<small>רכב עוזב: {selectedEffective.leftVehicle}</small>}</article></div><div className="v09-member-table"><div className="head"><span>רכב</span><span>כולל</span><span>Sync</span><span>Route</span><span>גורם</span></div>{selectedEffective.members.map(m=><div key={m.id}><b>{m.id}</b><span>{m.total}</span><span>{m.sync}</span><span>{m.route}</span><small>{m.reason}</small></div>)}</div><div className="v09-root-causes"><h3>גורמי שורש</h3>{selectedEffective.rootCauses.map(c=><div key={c.label}><span>{c.label}</span><div><i style={{width:`${c.sharePct}%`}}/></div><b>{c.sharePct}% · −{c.impactPoints}</b></div>)}</div><div className="v09-event-edit"><label>Template override<select value={edit.templateId} onChange={e=>updateEdit({templateId:e.target.value})}>{state.templates.filter(t=>t.family.toLowerCase()===selectedEffective.family).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="v09-recalc-note">מחושב לפני שמירה: <b>{selectedEffective.effectiveTotal}</b> · Sync {selectedEffective.effectiveSync} · Route {selectedEffective.effectiveRoute}</div><label>הערת תחקור<textarea value={edit.note} onChange={e=>updateEdit({note:e.target.value})}/></label><button className="v09-btn primary" onClick={saveEdit}><Save/>שמור שינוי</button></div></main></div>
  </div>;
}
