"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, Expand, Pause, Play, RefreshCcw, Volume2, VolumeX, X } from "lucide-react";
import { toast } from "sonner";
import type { DataMode, SoRelation, SyncTemplate } from "@/lib/bluewolf";
import { useWorkspace } from "../app-context";
import { DEFAULT_SO_GROUPING, type SoGroupingSettings } from "../v10/grouping";
import type { WindMode } from "../v10/wind";
import { loadNavigationDataset } from "./data-source";
import { provenanceFromSamples, type NavigationDataset } from "./navigation-data";
import { analyzeNavigationDataset, type NavigationDerivedAnalysis } from "./navigation-analyzer";
import { buildAnalysisHistory } from "./navigation-history";
import { GROUP_COLORS, V12LiveMap, type V12GroupKey, type V12OverlayKey } from "./map";
import { V12Timeline, type V12TimelineLayer } from "./timeline";

const EMPTY_DATASET: NavigationDataset = { samples: [], provenance: { source: "simulation", serverId: "", from: new Date(0).toISOString(), to: new Date(0).toISOString(), latestSampleAt: null, sampleCount: 0, vehicleCount: 0, samplingMedianSeconds: null, completenessPct: null, freshnessSeconds: null, warnings: [] } };
const overlayLabels: Record<V12OverlayKey,string>={trace:"עקבה",routes:"נתיבים",relations:"יחסים",scoreTrace:"עקבה לפי ציון"};
const layerLabels: Record<V12TimelineLayer,string>={total:"כולל",sync:"סנכרון",route:"נתיב"};
const tone=(score:number)=>score>=80?"good":score>=50?"medium":"low";
function settingsFrom(raw:unknown):SoGroupingSettings{const s=raw as{soGroupingMaxParallelLegs?:number;soGroupingMaxLateralLegs?:number;soGroupingMaxAngleDeg?:number};return{maxParallelLegs:s.soGroupingMaxParallelLegs??DEFAULT_SO_GROUPING.maxParallelLegs,maxLateralLegs:s.soGroupingMaxLateralLegs??DEFAULT_SO_GROUPING.maxLateralLegs,maxAngleDeg:s.soGroupingMaxAngleDeg??DEFAULT_SO_GROUPING.maxAngleDeg};}
function relationText(value:SoRelation){return value==="same"?"זהה":value==="opposite"?"הפוך":"מעורב";}
function templateRelations(template:SyncTemplate|undefined){return template?.soSpec?.relations??[];}
function dateTime(value:string|null){return value?new Intl.DateTimeFormat("he-IL",{dateStyle:"short",timeStyle:"medium"}).format(new Date(value)):"אין נתון";}
function groupExplanation(analysis:NavigationDerivedAnalysis,key:V12GroupKey){const group=analysis.groups[key];if(!group.members.length)return"לא זוהתה קבוצה מהניווט בטווח הנוכחי.";const worst=Object.values(group.vehicles).sort((a,b)=>b.routeDeviation-a.routeDeviation)[0];const parts=[`הציון מחושב מ־${group.members.length} רכבים`, `פער זמן מחזור ${group.periodErrorPct.toFixed(1)}%`, `פער קצב ${group.motionErrorPct.toFixed(1)}%`];if(worst)parts.push(`סטייה מרבית: רכב ${worst.id}, ${worst.routeDeviation.toFixed(1)} מ׳`);return parts.join(" · ")+".";}

export function OperatorViewV12({serverId,serverName,dataMode,onInvestigate}:{serverId:string;serverName:string;dataMode:DataMode;onInvestigate:()=>void}){
  const{state,save}=useWorkspace();const groupSettings=useMemo(()=>settingsFrom(state.settings),[state.settings]);
  const[dataset,setDataset]=useState<NavigationDataset>(EMPTY_DATASET);const[loadError,setLoadError]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[playhead,setPlayhead]=useState(()=>new Date());const[running,setRunning]=useState(true);const[windowMinutes,setWindowMinutes]=useState<30|60|90|120>(30);const[windMode,setWindMode]=useState<WindMode>("gusty");const[selectedGroup,setSelectedGroup]=useState<V12GroupKey|null>(null);const[selectedVehicle,setSelectedVehicle]=useState<number|null>(null);const[overlays,setOverlays]=useState<Record<V12OverlayKey,boolean>>({trace:true,routes:true,relations:true,scoreTrace:false});const[layers,setLayers]=useState<V12TimelineLayer[]>(["total","sync","route"]);const[visibleGroups,setVisibleGroups]=useState<V12GroupKey[]>(["si","so"]);const[cursor,setCursor]=useState(0);const[baseMap,setBaseMap]=useState(state.settings.defaultMap||state.mapServers.find((item)=>item.isDefault)?.id||"engineering");const[dialogOpen,setDialogOpen]=useState(false);const[previewId,setPreviewId]=useState("");const[applyMode,setApplyMode]=useState<"now"|"event-start">("now");const[muted,setMuted]=useState(false);const mapRef=useRef<HTMLDivElement>(null);
  const server=state.servers.find((item)=>item.id===serverId);const siTemplate=state.templates.find((item)=>item.id===(state.activeTemplateOverrides[`${serverId}:SI-NAV`]??"tpl-si-120"))??state.templates.find((item)=>item.family==="SI");const soTemplate=state.templates.find((item)=>item.id===(state.activeTemplateOverrides[`${serverId}:SO-NAV`]??"tpl-so-chain"))??state.templates.find((item)=>item.family==="SO");
  const options=useMemo(()=>({thresholds:state.thresholds,weights:state.weights,siTemplate,soTemplate,groupingSettings:groupSettings}),[state.thresholds,state.weights,siTemplate,soTemplate,groupSettings]);
  const analysis=useMemo(()=>analyzeNavigationDataset(dataset,options),[dataset,options]);const history=useMemo(()=>buildAnalysisHistory(dataset,options,36,12),[dataset,options]);
  const refresh=async(target?:Date)=>{setLoading(true);const to=dataMode==="simulation"?(target??playhead):new Date();const from=new Date(to.getTime()-windowMinutes*60_000);const result=await loadNavigationDataset({mode:dataMode,serverId,serverTag:server?.influxTag??serverId,from,to,grouping:groupSettings,windMode:dataMode==="simulation"?windMode:"off",influx:state.influx,targetPoints:5200});setDataset(result.dataset);setLoadError(result.error);setLoading(false);setCursor(Math.max(0,Math.min(35,history.length-1)));};
  useEffect(()=>{void refresh();},[dataMode,serverId,windowMinutes,windMode]);
  useEffect(()=>{if(!running||dataMode!=="simulation")return;const timer=window.setInterval(()=>{setPlayhead((current)=>{const next=new Date(current.getTime()+5000);void refresh(next);return next;});},5000);return()=>window.clearInterval(timer);},[running,dataMode,serverId,windowMinutes,windMode]);
  useEffect(()=>{if(dataMode!=="influx")return;const seconds=Math.max(2,state.influx.activePollSeconds||5);const timer=window.setInterval(()=>void refresh(),seconds*1000);return()=>window.clearInterval(timer);},[dataMode,serverId,windowMinutes,state.influx.activePollSeconds]);
  const currentGroup=selectedGroup?analysis.groups[selectedGroup]:null;const currentTemplate=selectedGroup?(selectedGroup==="si"?siTemplate:soTemplate):undefined;const candidates=selectedGroup?state.templates.filter((item)=>item.family===(selectedGroup==="si"?"SI":"SO")):[];const preview=candidates.find((item)=>item.id===previewId)??currentTemplate;const previewAnalysis=useMemo(()=>preview&&selectedGroup?analyzeNavigationDataset(dataset,{...options,siTemplate:selectedGroup==="si"?preview:siTemplate,soTemplate:selectedGroup==="so"?preview:soTemplate}):null,[preview,selectedGroup,dataset,options,siTemplate,soTemplate]);
  const noWindAnalysis=useMemo(()=>{if(dataMode!=="simulation"||windMode==="off")return null;const to=new Date(dataset.provenance.to);if(!Number.isFinite(to.getTime()))return null;const from=new Date(dataset.provenance.from);const noWind=loadNavigationDataset;void noWind;return null;},[dataMode,windMode,dataset]);
  const openTemplate=()=>{if(!selectedGroup||!currentTemplate)return;setPreviewId(currentTemplate.id);setDialogOpen(true);};const applyTemplate=async()=>{if(!selectedGroup||!preview)return;const groupId=selectedGroup==="si"?"SI-NAV":"SO-NAV",key=`${serverId}:${groupId}`;await save({...state,activeTemplateOverrides:{...state.activeTemplateOverrides,[key]:preview.id},templateApplications:{...state.templateApplications,[key]:{templateId:preview.id,mode:applyMode,appliedAt:new Date().toISOString()}}},"operator","template-v14",`${groupId}:${preview.id}`);setDialogOpen(false);toast.success("התבנית נשמרה; הציון חושב מחדש מאותו ניווט.");};
  const toggleLayer=(layer:V12TimelineLayer)=>setLayers((current)=>current.includes(layer)?(current.length===1?current:current.filter((item)=>item!==layer)):[...current,layer]);const toggleGroup=(key:V12GroupKey)=>setVisibleGroups((current)=>current.includes(key)?(current.length===1?current:current.filter((item)=>item!==key)):[...current,key]);
  const mapProfiles=state.mapServers.filter((item)=>item.enabled);const sourceLabel=dataMode==="simulation"?"סימולטור ניווט":"InfluxDB אמיתי";
  return <div className="v09-operator v12-operator"><header className="v09-page-head"><div><p className="eyebrow">מפעיל · SRS v1.4</p><h1>תמונה מבצעית</h1><p>{serverName} · מקור יחיד: {sourceLabel}. אין fallback בין המקורות.</p></div><div className="v09-actions">{dataMode==="simulation"&&<label className="v10-wind-select">רוח בסימולטור<select value={windMode} onChange={(event)=>setWindMode(event.target.value as WindMode)}><option value="off">ללא</option><option value="steady">קבועה</option><option value="gusty">משבים</option><option value="crosswind">צד</option></select></label>}<button onClick={()=>void refresh()}><RefreshCcw/>רענן</button><button onClick={onInvestigate}>לתחקור</button></div></header>
  {loadError&&<section className="v09-panel v12-data-error"><b>מקור הנתונים אינו זמין</b><p>{loadError}</p><small>המערכת אינה מציגה במקומו נתוני סימולציה.</small></section>}
  <div className="v09-kpis"><article><span>ציון כולל · SI</span><b className={analysis.available&&analysis.groups.si.members.length?tone(analysis.groups.si.score.total):""}>{analysis.available&&analysis.groups.si.members.length?analysis.groups.si.score.total:"—"}</b><small>{analysis.groups.si.members.length?`סנכרון ${analysis.groups.si.score.sync} · נתיב ${analysis.groups.si.score.route}`:"אין קבוצה מזוהה"}</small></article><article><span>ציון כולל · SO</span><b className={analysis.available&&analysis.groups.so.members.length?tone(analysis.groups.so.score.total):""}>{analysis.available&&analysis.groups.so.members.length?analysis.groups.so.score.total:"—"}</b><small>{analysis.groups.so.members.length?`סנכרון ${analysis.groups.so.score.sync} · נתיב ${analysis.groups.so.score.route}`:"אין קבוצה מזוהה"}</small></article><article><span>שלמות דגימות</span><b>{analysis.provenance.completenessPct==null?"—":`${analysis.provenance.completenessPct.toFixed(1)}%`}</b><small>{analysis.provenance.sampleCount} דגימות בפועל</small></article><article><span>מרווח דגימה חציוני</span><b>{analysis.provenance.samplingMedianSeconds==null?"—":`${analysis.provenance.samplingMedianSeconds.toFixed(1)}s`}</b><small>מחושב מחותמות הזמן</small></article><article><span>טריות דגימה אחרונה</span><b>{analysis.provenance.freshnessSeconds==null?"—":`${analysis.provenance.freshnessSeconds.toFixed(0)}s`}</b><small>{dateTime(analysis.provenance.latestSampleAt)}</small></article></div>
  <div className="v09-operator-grid"><section className="v09-panel v09-map-panel"><div className="v09-panel-head"><div><h2>מפה חיה</h2><p>{loading?"טוען ניווט...":`${analysis.provenance.vehicleCount} רכבים · ${analysis.provenance.sampleCount} דגימות`}</p></div><div className="v09-map-select"><select value={baseMap} onChange={(event)=>setBaseMap(event.target.value)}>{mapProfiles.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button aria-label="מסך מלא" onClick={()=>mapRef.current?.requestFullscreen?.()}><Expand/></button></div></div><div className="v09-overlay-bar">{(Object.keys(overlays) as V12OverlayKey[]).map((key)=><button key={key} className={overlays[key]?"active":""} onClick={()=>setOverlays((current)=>({...current,[key]:!current[key]}))}>{overlayLabels[key]}</button>)}</div><div ref={mapRef}><V12LiveMap dataset={dataset} analysis={analysis} history={history} baseMap={baseMap} overlays={overlays} selectedGroup={selectedGroup} selectedVehicle={selectedVehicle} onSelectGroup={setSelectedGroup} onSelectVehicle={(id,key)=>{setSelectedGroup(key);setSelectedVehicle(id);}}/></div></section>
  <aside className="v09-side v10-group-stack">{(["si","so"] as V12GroupKey[]).map((key)=>{const group=analysis.groups[key],selected=selectedGroup===key;return <article key={key} className={`v09-panel v10-group-card ${selected?"selected":""}`} onClick={()=>{setSelectedGroup(key);setSelectedVehicle(null);}}><div className="v09-group-title"><div><i style={{background:GROUP_COLORS[key]}}/><span><b>{group.name}</b><small>{group.members.length} רכבים · מקור {sourceLabel}</small></span></div><strong className={group.members.length?tone(group.score.total):""}>{group.members.length?group.score.total:"—"}</strong></div>{group.members.length?<><div className="v10-compact-scores"><span>סנכרון<b>{group.score.sync}</b></span><span>נתיב<b>{group.score.route}</b></span><span>מיקום<b>{group.score.position}</b></span></div>{selected&&<><p className="v09-cause">{groupExplanation(analysis,key)}</p>{key==="so"&&analysis.groupingNotes.length?<div className="v10-grouping-evidence"><b>ראיות קיבוץ</b>{analysis.groupingNotes.slice(0,4).map((note,index)=><small key={index}>{note}</small>)}</div>:null}<div className="v09-members">{group.members.map((id)=>{const evidence=group.vehicles[id];return <button key={id} className={selectedVehicle===id?"active":""} onClick={(event)=>{event.stopPropagation();setSelectedVehicle(id);}}><i style={{background:GROUP_COLORS[key]}}/><span>רכב {id}<small>סטייה {evidence.routeDeviation.toFixed(1)} מ׳ · מחזור {evidence.periodSec?.toFixed(1)??"—"} שנ׳ · רוח משוערת {evidence.wind.speedKnots.toFixed(1)} קשר @ {evidence.wind.bearingDeg.toFixed(0)}°</small></span><b>{evidence.sync}</b></button>})}</div><div className="v10-wind-impact"><b>שערוך רוח/הפרעה בלבד</b><small>הערכים נגזרים משארית בין וקטור המהירות הנמדד למסלול/מהירות הנומינליים שנלמדו מהניווט. הם אינם נכנסים ישירות לציון.</small></div><button className="primary v10-card-template-button" onClick={(event)=>{event.stopPropagation();openTemplate();}}>החלפת תבנית לקבוצה</button></>}</>:<p>לא זוהתה קבוצה מהדגימות; לא מוצג ציון חלופי.</p>}</article>})}
  <article className="v09-panel"><div className="v09-panel-head"><div><h3>התראות למפעיל</h3><p>כולן נגזרות מראיות הניווט והספים.</p></div><button className="v09-icon-button" onClick={()=>setMuted((value)=>!value)}>{muted?<VolumeX/>:<Volume2/>}</button></div>{analysis.alerts.map((alert)=><div key={alert.id} className={`v09-alert ${alert.severity}`}><b>{alert.title}</b><p>{alert.detail}</p>{alert.evidence.map((line,index)=><small key={index}>{line}</small>)}</div>)}</article></aside></div>
  <section className="v09-panel v09-chart-panel"><div className="v09-panel-head"><div><h2>ציר ציונים</h2><p>כל נקודה נבנתה מחדש מחלון ניווט היסטורי.</p></div><div className="v09-window-picker">{([30,60,90,120] as const).map((value)=><button key={value} className={windowMinutes===value?"active":""} onClick={()=>setWindowMinutes(value)}>{value} דק׳</button>)}</div></div><div className="v09-chart-toggles v10-chart-filters"><div><b>קבוצות</b>{(["si","so"] as V12GroupKey[]).map((key)=><button key={key} className={visibleGroups.includes(key)?"active":""} onClick={()=>toggleGroup(key)}>{key.toUpperCase()}</button>)}</div><div><b>מדדים</b>{(["total","sync","route"] as V12TimelineLayer[]).map((layer)=><button key={layer} className={layers.includes(layer)?"active":""} onClick={()=>toggleLayer(layer)}>{layerLabels[layer]}</button>)}</div></div><V12Timeline history={history} layers={layers} groups={visibleGroups} cursor={cursor} onCursor={setCursor}/></section>
  {dataMode==="simulation"&&<section className="v09-panel v09-global-time"><div><button className="v09-icon-button" onClick={()=>setRunning((value)=>!value)}>{running?<Pause/>:<Play/>}</button><b>זמן סימולציה</b><span>{dateTime(playhead.toISOString())}</span></div><input type="range" min="0" max="1800" value="1800" onChange={(event)=>{setRunning(false);const offset=1800-Number(event.target.value);const next=new Date(Date.now()-offset*1000);setPlayhead(next);void refresh(next);}}/></section>}
  {dialogOpen&&selectedGroup&&currentGroup&&<div className="v09-modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)setDialogOpen(false);}}><section className="v09-template-sheet" role="dialog" aria-modal="true"><header><div><p className="eyebrow">החלפת תבנית</p><h2>{currentGroup.name}</h2><p>ההשוואה מחושבת מחדש מאותו dataset; רק חוק התבנית משתנה.</p></div><button onClick={()=>setDialogOpen(false)}><X/></button></header><div className="v09-sheet-scroll"><div className="v09-template-choices">{candidates.map((item)=><button key={item.id} className={preview?.id===item.id?"active":""} onClick={()=>setPreviewId(item.id)}><b>{item.name}</b><span>{item.constellation}</span></button>)}</div>{previewAnalysis&&<div className="v09-expected"><span>כולל צפוי<b>{previewAnalysis.groups[selectedGroup].score.total}</b></span><span>סנכרון צפוי<b>{previewAnalysis.groups[selectedGroup].score.sync}</b></span><span>נתיב<b>{previewAnalysis.groups[selectedGroup].score.route}</b></span><span>{selectedGroup==="so"?templateRelations(preview).map(relationText).join(" · "):preview.values.map((v)=>`${v}°`).join(" · ")}</span></div>}<div className="v09-mode"><b>ממתי להחיל?</b><button className={applyMode==="now"?"active":""} onClick={()=>setApplyMode("now")}>מעכשיו</button><button className={applyMode==="event-start"?"active":""} onClick={()=>setApplyMode("event-start")}>מתחילת האירוע</button></div></div><footer><button onClick={()=>setDialogOpen(false)}>ביטול</button><button className="primary" onClick={applyTemplate}><Check/>החל</button></footer></section></div>}
  </div>;
}
