"use client";

import { useState } from "react";
import { PlayCircle, ShieldCheck } from "lucide-react";
import { DEFAULT_INFLUX_MAPPINGS } from "@/lib/bluewolf";
import { normalizeInfluxRecords, type InfluxMappedRecord } from "@/lib/influx-navigation";
import { useWorkspace } from "../app-context";
import { DEFAULT_SO_GROUPING, soPairCompatibility } from "../v10/grouping";
import { windForVehicle } from "../v10/wind";
import { analyzeNavigationDataset } from "./navigation-analyzer";
import { buildAnalysisHistory, deriveEvents } from "./navigation-history";
import { generateSimulationDataset, simulationHistoryBounds, simulationTickAt, simulatorGroundTruthAt } from "./navigation-data";
import { generateUniqueSoLayouts } from "../v10/template-builder";

type Result={name:string;category:string;pass:boolean;detail:string};
const bearingDiff=(a:number,b:number)=>{const d=Math.abs(((a-b+180)%360+360)%360-180);return d;};
function ids(value:number[]){return [...value].sort((a,b)=>a-b).join(",");}
function fixtureRecords(systemKey:string,value:string,time:string):InfluxMappedRecord[]{return[{systemKey,time,value,tags:{vehicle:"fixture-101"}}];}

export function V12SystemTests(){const{state}=useWorkspace();const[results,setResults]=useState<Result[]>([]),[running,setRunning]=useState(false),[analyses,setAnalyses]=useState(0),[elapsed,setElapsed]=useState<number|null>(null);const grouping={maxParallelLegs:(state.settings as typeof state.settings&{soGroupingMaxParallelLegs?:number}).soGroupingMaxParallelLegs??DEFAULT_SO_GROUPING.maxParallelLegs,maxLateralLegs:(state.settings as typeof state.settings&{soGroupingMaxLateralLegs?:number}).soGroupingMaxLateralLegs??DEFAULT_SO_GROUPING.maxLateralLegs,maxAngleDeg:(state.settings as typeof state.settings&{soGroupingMaxAngleDeg?:number}).soGroupingMaxAngleDeg??DEFAULT_SO_GROUPING.maxAngleDeg};const options={thresholds:state.thresholds,weights:state.weights,siTemplate:state.templates.find((t)=>t.id==="tpl-si-120")??state.templates.find((t)=>t.family==="SI"),soTemplate:state.templates.find((t)=>t.id==="tpl-so-chain")??state.templates.find((t)=>t.family==="SO"),groupingSettings:grouping};
const run=async(stress=180)=>{setRunning(true);await new Promise((resolve)=>setTimeout(resolve,0));const start=performance.now(),out:Result[]=[];let count=0;const add=(name:string,category:string,pass:boolean,detail:string)=>out.push({name,category,pass,detail});try{
  const now=new Date();for(const serverId of ["1","2","3"]){const center=new Date(now.getTime()-(Number(serverId)*37+12)*60_000),dataset=generateSimulationDataset({serverId,from:new Date(center.getTime()-12*60_000),to:center,grouping,windMode:"gusty",targetPoints:2600}),analysis=analyzeNavigationDataset(dataset,options),gt=simulatorGroundTruthAt(serverId,center,grouping);count++;const detected=[...Object.keys(analysis.current)].map(Number);add(`שרת ${serverId} · רכבים פעילים`,`Simulator→Analyzer→GT`,gt.activeVehicles.every((id)=>detected.includes(id)),`GT ${ids(gt.activeVehicles)} · ניתוח ${ids(detected)}`);add(`שרת ${serverId} · טווח ציונים`,`Scoring`,[analysis.groups.si.score,analysis.groups.so.score].every((score)=>Object.values(score).every((value)=>Number.isFinite(value)&&value>=0&&value<=100)),`SI ${analysis.groups.si.score.total} · SO ${analysis.groups.so.score.total}`);if(serverId==="2")add("שרת 2 · היפודרום לא חוקי נשאר בחוץ","Grouping",gt.ungroupedVehicles.every((id)=>analysis.ungroupedVehicles.includes(id)),`GT מחוץ ${ids(gt.ungroupedVehicles)} · בפועל ${ids(analysis.ungroupedVehicles)}`);if(serverId==="3")add("שרת 3 · SO מזוהה מהניווט","Grouping",analysis.groups.so.members.length>=2,`SO בפועל ${ids(analysis.groups.so.members)}`);
    const gtVehicle=gt.activeVehicles.find((id)=>analysis.groups.so.vehicles[id]||analysis.groups.si.vehicles[id]);if(gtVehicle){const evidence=analysis.groups.so.vehicles[gtVehicle]??analysis.groups.si.vehicles[gtVehicle],truth=windForVehicle(serverId,simulationTickAt(center),gtVehicle,"gusty");add(`שרת ${serverId} · שערוך רוח מול GT`,`Wind estimator`,Math.abs(evidence.wind.speedKnots-truth.trueKnots)<=12&&bearingDiff(evidence.wind.bearingDeg,truth.trueBearingDeg)<=85,`GT ${truth.trueKnots.toFixed(1)}kt @ ${truth.trueBearingDeg.toFixed(0)}° · estimate ${evidence.wind.speedKnots.toFixed(1)}kt @ ${evidence.wind.bearingDeg.toFixed(0)}°`);}}
  const invalid=soPairCompatibility({kind:"single",center:{x:0,y:0},radius:25,legLength:100,rotationDeg:0},{kind:"single",center:{x:30,y:100},radius:25,legLength:100,rotationDeg:45},grouping),valid=soPairCompatibility({kind:"single",center:{x:0,y:0},radius:25,legLength:100,rotationDeg:0},{kind:"single",center:{x:120,y:5},radius:25,legLength:100,rotationDeg:5},grouping);add("חוק קיבוץ · valid/invalid","Production grouping",valid.valid&&!invalid.valid,`valid=${valid.explanation} | invalid=${invalid.explanation}`);
  const layouts=generateUniqueSoLayouts(2,2).map((layout)=>layout.join("-"));add("SO layout · הסרת תמונת מראה","Template builder",new Set(layouts).size===layouts.length&&layouts.length>0,`${layouts.length} layouts ייחודיים`);
  const bounds=simulationHistoryBounds(now),month=generateSimulationDataset({serverId:"2",from:bounds.from,to:bounds.to,grouping,windMode:"gusty",targetPoints:6500}),monthAgain=generateSimulationDataset({serverId:"2",from:bounds.from,to:bounds.to,grouping,windMode:"gusty",targetPoints:6500});add("30 יום · שליפה דטרמיניסטית","Historical simulator",month.samples.length>0&&month.samples.length===monthAgain.samples.length&&month.samples[0]?.timestamp===monthAgain.samples[0]?.timestamp&&month.samples.at(-1)?.timestamp===monthAgain.samples.at(-1)?.timestamp,`${month.samples.length} דגימות · ${month.provenance.from} → ${month.provenance.to}`);
  const sixHours=generateSimulationDataset({serverId:"3",from:new Date(now.getTime()-6*60*60_000),to:now,grouping,windMode:"gusty",targetPoints:5500}),history=buildAnalysisHistory(sixHours,options,80,12),events=deriveEvents(history,state.thresholds);count+=history.length;add("אירועים · נגזרים מהיסטוריית NAV","Investigation",events.length>0&&events.every((event)=>event.frames.length>0&&event.startReason.length>10&&event.endReason.length>10),`${events.length} אירועים מתוך ${history.length} frames`);
  const t="2026-09-06T12:00:00.000Z",mapped=DEFAULT_INFLUX_MAPPINGS.filter((m)=>["uniqueVehicleId","latitude","longitude","velocityNorth","velocityEast"].includes(m.systemKey)).map((mapping)=>({mapping,records:fixtureRecords(mapping.systemKey,mapping.systemKey==="uniqueVehicleId"?"101":mapping.systemKey==="latitude"?"31.7":mapping.systemKey==="longitude"?"34.8":mapping.systemKey==="velocityNorth"?"12":"3",t)})),normalized=normalizeInfluxRecords(mapped,2);add("Influx fixture · אותו normalizer","Influx adapter",normalized.samples.length===1&&normalized.samples[0].vehicleId===101&&normalized.samples[0].velocityNorth===12,`${normalized.samples.length} normalized sample`);
  const empty=analyzeNavigationDataset({samples:[],provenance:{source:"influx",serverId:"1",from:t,to:t,latestSampleAt:null,sampleCount:0,vehicleCount:0,samplingMedianSeconds:null,completenessPct:null,freshnessSeconds:null,warnings:["fixture no data"]}},options);add("אין נתונים · אין ציון חלופי","Provenance",!empty.available&&empty.groups.si.members.length===0&&empty.groups.so.members.length===0,"No simulator fallback");
  for(let i=0;i<stress;i++){const serverId=String(i%3+1),center=new Date(now.getTime()-(i*173%30_000)*60_000),data=generateSimulationDataset({serverId,from:new Date(center.getTime()-6*60_000),to:center,grouping,windMode:i%4===0?"off":i%4===1?"steady":i%4===2?"gusty":"crosswind",targetPoints:520}),analysis=analyzeNavigationDataset(data,options);count++;if(!Object.values(analysis.groups.si.score).every(Number.isFinite)||!Object.values(analysis.groups.so.score).every(Number.isFinite)){add(`stress ${i}`,"Stress",false,"non-finite score");break;}}
  add(`${stress} חלונות stress אמיתיים","Stress",!out.some((item)=>item.category==="Stress"&&!item.pass),`${stress} datasets עברו simulator→raw NAV→analyzer`);
}catch(error){add("הרצת מערכת","Runtime",false,error instanceof Error?error.message:"unknown error");}setResults(out);setAnalyses(count);setElapsed(performance.now()-start);setRunning(false);};const passed=results.filter((item)=>item.pass).length;
return <div><header className="v09-section-header"><div><p className="eyebrow">E2E SYSTEM TESTS · SRS v1.4</p><h2>בדיקות מערכת אמיתיות</h2><p>ה־GT משמש רק להשוואה אחרי שה־production analyzer סיים. הוא אינו קלט לאלגוריתם.</p></div><div className="v09-actions"><button disabled={running} onClick={()=>void run(180)}><PlayCircle/>{running?"רץ...":"הרץ E2E"}</button><button className="primary" disabled={running} onClick={()=>void run(1000)}><ShieldCheck/>Stress 1000</button></div></header>{results.length?<><div className="v09-test-kpis"><b className={passed===results.length?"good":"low"}>{passed}/{results.length}</b><span>{analyses} ניתוחי production · {elapsed?.toFixed(0)} ms</span></div><div className="v09-test-grid">{results.map((result,index)=><article key={`${result.name}-${index}`}><header><b>{result.name}</b><span className={result.pass?"pass":"fail"}>{result.pass?"PASS":"FAIL"}</span></header><small>{result.category}</small><p>{result.detail}</p></article>)}</div></>:<div className="v09-empty-tests"><ShieldCheck/><b>טרם הורץ</b><p>הבדיקות מייצרות ניווט, מנתחות אותו ומשוות ל־GT נפרד, כולל חודש היסטוריה ו־Influx fixture.</p></div>}</div>;
}
