import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();

test('SO-01/SO-02 authoring is generated by route counts then direct placement', async () => {
  const source = await readFile(path.join(root, 'components/bluewolf/so-template-governance-workbench.tsx'), 'utf8');
  const governance = await readFile(path.join(root, 'components/bluewolf/developer-governance-workbench.tsx'), 'utf8');

  assert.match(source, /data-requirements="SO-01 SO-02 GEO-01 GEO-02"/);
  assert.match(source, /data-testid=\{`so-count-\$\{kind\}`\}/);
  assert.match(source, /\["single", "double"\] as const/);
  assert.match(source, /<Minus \/>/);
  assert.match(source, /<Plus \/>/);
  assert.match(source, /generateUniqueSoOrders/);
  assert.match(source, /כל הסדרים השונים/);
  assert.match(source, /buildSoSmileGeometry/);
  assert.match(source, /pointAtSoPhase/);
  assert.match(source, /soPhasesForRoute/);
  assert.match(source, /placeSoVehicle/);
  assert.match(source, /toggleSoVehicleDirection/);
  assert.match(source, /deriveSoRelations/);
  assert.match(source, /onMouseEnter/);
  assert.match(source, /fillOpacity=\{existing \? 1 : hovered \? \.25 : 0\}/);
  assert.doesNotMatch(source, /SingleRouteShape|DoubleRouteShape|slotGeometry/);
  assert.doesNotMatch(source, /SelectItem value="same"|SelectItem value="opposite"|SelectItem value="mixed"/);

  assert.match(governance, /SoTemplateGovernanceWorkbench/);
  assert.match(governance, /template-governance-workbench.*v04-family-switch/s);
  assert.match(governance, /button:nth-child\(2\)/);
});
