import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const read=(path)=>fs.readFileSync(path,"utf8");

test("official SRS keeps single-NAV truth and v1.7 simplified architecture",()=>{const current=read("docs/BLUE_WOLF_SRS_CURRENT.md"),v14=read("docs/BLUE_WOLF_SRS_CHANGESET_2026-09-06_V1_4.md"),v17=read("docs/BLUE_WOLF_ARCHITECTURE_V1_7_SIMPLIFIED_CANONICAL.md");assert.match(current,/V1_4/);assert.match(current,/V1_7/);assert.match(v14,/No operational, investigation, PDF or test result may display/);assert.match(v14,/30 days of historical data/);assert.match(v14,/never silently fall back to simulator/i);assert.match(v17,/InfluxDB is authoritative historical NAV storage/);assert.match(v17,/Python CoreSession/);});

test("active dashboard uses v12 source-driven screens and has no static notification feed",()=>{const page=read("app/page.tsx"),shell=read("components/bluewolf/dashboard-app-v12.tsx");assert.match(page,/DashboardAppV12/);assert.match(shell,/OperatorViewV12/);assert.match(shell,/InvestigationViewV12/);assert.match(shell,/DeveloperViewV12/);assert.match(shell,/v0\.14/);assert.match(shell,/SRS v1\.7/);assert.match(shell,/Python Core/);assert.doesNotMatch(shell,/notifications\s*=/);});

test("operator scores, quality and wind are derived from dataset provenance",()=>{const source=read("components/bluewolf/v12/operator.tsx");assert.match(source,/loadNavigationDataset/);assert.match(source,/analyzeNavigationDataset/);assert.match(source,/buildAnalysisHistory/);assert.match(source,/completenessPct/);assert.match(source,/samplingMedianSeconds/);assert.match(source,/groups\.si\.score\.total/);assert.match(source,/wind\.speedKnots/);assert.doesNotMatch(source,/>96%</);assert.doesNotMatch(source,/>4\.2s/);assert.match(source,/אין fallback/);});

test("raw simulator provides deterministic 30-day timestamped navigation",()=>{const source=read("components/bluewolf/v12/navigation-data.ts");assert.match(source,/SIMULATION_HISTORY_DAYS = 30/);assert.match(source,/timestamp: timestamp\.toISOString/);assert.match(source,/velocityNorth/);assert.match(source,/velocityEast/);assert.match(source,/simulatorGroundTruthAt/);assert.match(source,/generateSimulationDataset/);});

test("navigation analyzer surface delegates to the single application core adapter",()=>{const wrapper=read("components/bluewolf/v12/navigation-analyzer.ts"),adapter=read("lib/algorithm-core-adapter.ts"),compat=read("packages/bluewolf-core/src/analyzer.ts");assert.match(wrapper,/algorithm-core-adapter/);assert.match(adapter,/analyzeNavigationDataset/);assert.match(compat,/groupByVehicle\(samples|groupByVehicle\(dataset\.samples/);assert.match(compat,/windEstimate/);assert.match(compat,/alertsFromAnalysis/);assert.doesNotMatch(wrapper,/getV09Scenario/);assert.doesNotMatch(wrapper,/windForVehicle/);});

test("Influx mode performs a real query, has no TTAG contract and never falls back to simulator",()=>{const route=read("app/api/influx/query/route.ts"),loader=read("components/bluewolf/v12/data-source.ts"),normalizer=read("lib/influx-navigation.ts"),settings=read("components/bluewolf/v09/infra-settings.tsx");assert.match(route,/\/api\/v2\/query/);assert.match(route,/normalizeInfluxRecords/);assert.match(route,/server_id/);assert.doesNotMatch(route,/ttag/i);assert.match(normalizer,/uniqueVehicleId/);assert.match(normalizer,/latitude/);assert.match(normalizer,/velocityNorth/);assert.match(loader,/\/api\/influx\/query/);assert.match(loader,/אין fallback לסימולטור/);assert.doesNotMatch(loader,/ttag/i);assert.match(settings,/אין TTAG/);});

test("historical investigation uses selected source range and adapter-derived events",()=>{const source=read("components/bluewolf/v12/investigation.tsx"),history=read("components/bluewolf/v12/navigation-history.ts"),adapter=read("lib/algorithm-core-adapter.ts");assert.match(source,/new Date\(from\)/);assert.match(source,/new Date\(to\)/);assert.match(source,/loadNavigationDataset/);assert.match(source,/deriveEvents/);assert.match(source,/30 ימים/);assert.match(source,/EventEvidenceMap events=\{events\} selected=\{selected\}/);assert.match(history,/algorithm-core-adapter/);assert.match(adapter,/deriveEvents/);});

test("system tests execute production data path against separate simulator GT",()=>{const source=read("components/bluewolf/v12/system-tests.tsx");assert.match(source,/simulatorGroundTruthAt/);assert.match(source,/generateSimulationDataset/);assert.match(source,/analyzeNavigationDataset/);assert.match(source,/deriveEvents/);assert.match(source,/normalizeInfluxRecords/);assert.match(source,/Stress 1000/);assert.match(source,/GT/);});

test("SO count-first builder and engineering map fixes remain active",()=>{const builder=read("components/bluewolf/v10/template-builder.tsx"),css=read("app/v11.css");assert.match(builder,/generateUniqueSoLayouts/);assert.match(builder,/singleCount/);assert.match(builder,/doubleCount/);assert.match(builder,/clickSlot/);assert.match(css,/v09-gt-map pattern path/);assert.match(css,/fill:none!important/);});

test("compact Core checkpoint is isolated from navigation history",()=>{const schema=read("db/schema.ts"),route=read("app/api/core/checkpoint/route.ts"),session=read("core/src/bluewolf_core/session_v17.py");assert.match(schema,/sqliteTable\("core_checkpoints"/);assert.match(route,/checkpointBase64/);assert.match(session,/route\.pop\("history"/);assert.match(session,/hydrate_recovery_history/);assert.match(session,/recovery_history_seconds/);});
