import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const read=(path)=>fs.readFileSync(path,"utf8");

test("official SRS points to v1.4 newest-wins contract",()=>{const current=read("docs/BLUE_WOLF_SRS_CURRENT.md"),amendment=read("docs/BLUE_WOLF_SRS_CHANGESET_2026-09-06_V1_4.md");assert.match(current,/V1_4/);assert.match(current,/single-navigation-truth/i);assert.match(amendment,/No operational, investigation, PDF or test result may display/);assert.match(amendment,/30 days of historical data/);assert.match(amendment,/never silently fall back to simulator/i);});

test("active dashboard uses v12 source-driven screens and has no static notification feed",()=>{const page=read("app/page.tsx"),shell=read("components/bluewolf/dashboard-app-v12.tsx");assert.match(page,/DashboardAppV12/);assert.match(shell,/OperatorViewV12/);assert.match(shell,/InvestigationViewV12/);assert.match(shell,/DeveloperViewV12/);assert.doesNotMatch(shell,/Wind estimate/);assert.doesNotMatch(shell,/notifications\s*=/);});

test("operator scores, quality and wind are derived from dataset provenance",()=>{const source=read("components/bluewolf/v12/operator.tsx");assert.match(source,/loadNavigationDataset/);assert.match(source,/analyzeNavigationDataset/);assert.match(source,/buildAnalysisHistory/);assert.match(source,/completenessPct/);assert.match(source,/samplingMedianSeconds/);assert.match(source,/groups\.si\.score\.total/);assert.match(source,/wind\.speedKnots/);assert.doesNotMatch(source,/>96%</);assert.doesNotMatch(source,/>4\.2s/);assert.match(source,/אין fallback/);});

test("raw simulator provides deterministic 30-day timestamped navigation",()=>{const source=read("components/bluewolf/v12/navigation-data.ts");assert.match(source,/SIMULATION_HISTORY_DAYS = 30/);assert.match(source,/timestamp: timestamp\.toISOString/);assert.match(source,/velocityNorth/);assert.match(source,/velocityEast/);assert.match(source,/simulatorGroundTruthAt/);assert.match(source,/generateSimulationDataset/);});

test("production analyzer derives route sync total wind and alerts from raw samples",()=>{const source=read("components/bluewolf/v12/navigation-analyzer.ts");assert.match(source,/groupByVehicle\(dataset\.samples\)/);assert.match(source,/siTemplateScores/);assert.match(source,/soTemplateScores/);assert.match(source,/routeEvidence/);assert.match(source,/windEstimate/);assert.match(source,/alertsFromAnalysis/);assert.match(source,/largestCompatibleComponent/);assert.doesNotMatch(source,/getV09Scenario/);assert.doesNotMatch(source,/windForVehicle/);});

test("Influx mode performs a real query and shared normalization without simulator fallback",()=>{const route=read("app/api/influx/query/route.ts"),loader=read("components/bluewolf/v12/data-source.ts"),normalizer=read("lib/influx-navigation.ts");assert.match(route,/\/api\/v2\/query/);assert.match(route,/normalizeInfluxRecords/);assert.match(normalizer,/uniqueVehicleId/);assert.match(normalizer,/latitude/);assert.match(normalizer,/velocityNorth/);assert.match(loader,/\/api\/influx\/query/);assert.match(loader,/אין fallback לסימולטור/);assert.doesNotMatch(loader,/generateSimulationDataset\(.*mode === "influx"/s);});

test("historical investigation uses selected source range and navigation-derived events",()=>{const source=read("components/bluewolf/v12/investigation.tsx"),history=read("components/bluewolf/v12/navigation-history.ts");assert.match(source,/new Date\(from\)/);assert.match(source,/new Date\(to\)/);assert.match(source,/loadNavigationDataset/);assert.match(source,/deriveEvents/);assert.match(source,/30 ימים/);assert.match(source,/EventEvidenceMap events=\{events\} selected=\{selected\}/);assert.match(history,/compareMembership/);assert.match(history,/routeSignature/);assert.match(history,/periodErrorPct/);});

test("system tests execute production data path against separate simulator GT",()=>{const source=read("components/bluewolf/v12/system-tests.tsx");assert.match(source,/simulatorGroundTruthAt/);assert.match(source,/generateSimulationDataset/);assert.match(source,/analyzeNavigationDataset/);assert.match(source,/deriveEvents/);assert.match(source,/normalizeInfluxRecords/);assert.match(source,/Stress 1000/);assert.match(source,/GT/);});

test("SO count-first builder and engineering map fixes remain active",()=>{const builder=read("components/bluewolf/v10/template-builder.tsx"),css=read("app/v11.css");assert.match(builder,/generateUniqueSoLayouts/);assert.match(builder,/singleCount/);assert.match(builder,/doubleCount/);assert.match(builder,/clickSlot/);assert.match(css,/v09-gt-map pattern path/);assert.match(css,/fill:none!important/);});
