"use client";

import { useMemo, useState } from "react";
import { Database, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";

import type { InfluxFieldMapping, VehicleIdRange } from "@/lib/bluewolf";
import { useWorkspace } from "../app-context";
import { fixedVehicleTypes } from "./map";

export function V09Influx() {
  const {state,save}=useWorkspace();const[url,setUrl]=useState(state.influx.url);const[organization,setOrganization]=useState(state.influx.organization);const[token,setToken]=useState(state.influx.token);const[mappings,setMappings]=useState<InfluxFieldMapping[]>(structuredClone(state.influx.mappings));const[status,setStatus]=useState<{tone:"idle"|"testing"|"ok"|"bad";text:string}>({tone:"idle",text:"טרם נבדק"});
  const patch=(index:number,next:Partial<InfluxFieldMapping>)=>setMappings(current=>current.map((item,i)=>i===index?{...item,...next}:item));
  const test=async()=>{setStatus({tone:"testing",text:"בודק Health + Auth..."});try{const response=await fetch("/api/influx/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url,organization,token})});const body=await response.json() as {ok?:boolean;authenticated?:boolean;error?:string};if(!response.ok||!body.ok)throw new Error(body.error??`HTTP ${response.status}`);setStatus({tone:"ok",text:body.authenticated?"Health + authentication עברו":"Health עבר; חסרים פרטי Auth"});}catch(error){setStatus({tone:"bad",text:`לא ניתן להתחבר: ${error instanceof Error?error.message:"unknown"}`});}};
  return <div><header className="v09-section-header"><div><p className="eyebrow">DATA ADAPTER</p><h2>InfluxDB 2</h2><p>חיבור ומיפוי מטריקות. זיהוי שרת נעשה לפי server_id; אין TTAG בארכיטקטורה.</p></div><div className="v09-actions"><button onClick={test}><Database/>בדיקת חיבור</button><button className="primary" onClick={async()=>{await save({...state,influx:{...state.influx,url,organization,token,mappings}},"influx","save-v17",url);toast.success("Influx נשמר")}}><Save/>שמור</button></div></header>
    <section className="v09-panel"><h3>1 · פרטי חיבור</h3><div className="v09-influx-connection"><label>URL<input value={url} onChange={event=>setUrl(event.target.value)}/></label><label>Organization<input value={organization} onChange={event=>setOrganization(event.target.value)}/></label><label>Token<input type="password" value={token} onChange={event=>setToken(event.target.value)}/></label><label>Polling<select value={state.influx.activePollSeconds}><option>2</option><option>5</option><option>10</option></select></label></div><div className={`v09-connection-result ${status.tone}`}>{status.text}</div></section>
    <section className="v09-panel"><div className="v09-panel-head"><div><h3>2 · מיפוי מטריקות</h3><p>Bucket / Measurement / Key-Field / Transform / Fill לכל שדה. ה־Join נעשה לפי מזהה רכב וזמן.</p></div><span>{mappings.length} שדות</span></div><div className="v09-mapping-cards">{mappings.map((item,index)=><article key={item.systemKey}><header><b>{item.label}</b><code>{item.systemKey}</code></header><div><label>Bucket<input value={item.bucket} onChange={event=>patch(index,{bucket:event.target.value})}/></label><label>Measurement<input value={item.measurement} onChange={event=>patch(index,{measurement:event.target.value})}/></label><label>Key / Field<input value={item.key} onChange={event=>patch(index,{key:event.target.value})}/></label><label>Mode<select value={item.valueMode} onChange={event=>patch(index,{valueMode:event.target.value as InfluxFieldMapping["valueMode"]})}><option value="as-is">As-Is</option><option value="special">Map Value</option></select></label><label>Fill<select value={item.fillMode} onChange={event=>patch(index,{fillMode:event.target.value as InfluxFieldMapping["fillMode"]})}><option value="linear">Linear</option><option value="forward-fill">Forward fill</option></select></label>{item.valueMode==="special"&&<label>Source → Target<input value={`${item.sourceValue} → ${item.mappedValue}`} onChange={event=>{const parts=event.target.value.split("→");patch(index,{sourceValue:parts[0]?.trim()??"",mappedValue:parts[1]?.trim()??""})}}/></label>}</div></article>)}</div></section>
  </div>;
}

function normalizeRanges(ranges: VehicleIdRange[]|undefined,min:number,max:number){return ranges?.length?ranges:[{min,max}];}

export function V09Settings() {
  const{state,save}=useWorkspace();const types=useMemo(()=>fixedVehicleTypes(state.vehicleTypes),[state.vehicleTypes]);const[draftTypes,setDraftTypes]=useState(types);const[servers,setServers]=useState(structuredClone(state.servers));const[mapServers,setMapServers]=useState(structuredClone(state.mapServers));
  const patchType=(id:string,patch:Partial<(typeof draftTypes)[number]>)=>setDraftTypes(current=>current.map(type=>type.id===id?{...type,...patch}:type));
  const setRanges=(id:string,ranges:VehicleIdRange[])=>{const type=draftTypes.find(item=>item.id===id);if(!type)return;patchType(id,{idRanges:ranges,minId:ranges[0]?.min??type.minId,maxId:ranges.at(-1)?.max??type.maxId});};
  return <div><header className="v09-section-header"><div><p className="eyebrow">SYSTEM SETTINGS</p><h2>הגדרות מערכת</h2><p>שרתים, מפות וסוגי רכב מופרדים. מזהה השרת עצמו הוא זהות המקור ב־Influx.</p></div><button className="primary" onClick={async()=>{await save({...state,vehicleTypes:draftTypes,servers,mapServers},"settings","save-v17","structured settings");toast.success("ההגדרות נשמרו")}}><Save/>שמור</button></header>
    <section className="v09-panel"><h3>שרתים</h3><p>בחירת שרת במסך המפעיל מעירה אותו מיד ל־polling של 5 שניות; אין שדה TTAG נפרד.</p><div className="v09-server-cards">{servers.map((server,index)=><article key={server.id}><span className="v09-server-number">{index+1}</span><label>שם<input value={server.name} onChange={event=>setServers(current=>current.map(item=>item.id===server.id?{...item,name:event.target.value}:item))}/></label><label>מזהה מקור<code>{server.id}</code></label><label className="v09-check"><input type="checkbox" checked={server.enabled} onChange={event=>setServers(current=>current.map(item=>item.id===server.id?{...item,enabled:event.target.checked}:item))}/>פעיל</label><p>{index===0?"Baseline clean SI/SO":index===1?"Join/leave/disconnect + co-located SO":"+22% period + geometry revision + SO→SI"}</p></article>)}</div></section>
    <section className="v09-panel"><h3>מקורות מפה</h3><div className="v09-map-source-cards">{mapServers.map((source)=><article key={source.id}><label>שם<input value={source.name} onChange={event=>setMapServers(current=>current.map(item=>item.id===source.id?{...item,name:event.target.value}:item))}/></label><label>סוג<select value={source.kind} onChange={event=>setMapServers(current=>current.map(item=>item.id===source.id?{...item,kind:event.target.value as typeof source.kind}:item))}><option value="engineering">Engineering</option><option value="wms">WMS</option><option value="wmts">WMTS</option><option value="xyz">XYZ</option></select></label><label>URL<input value={source.urlTemplate} onChange={event=>setMapServers(current=>current.map(item=>item.id===source.id?{...item,urlTemplate:event.target.value}:item))}/></label><label className="v09-check"><input type="checkbox" checked={source.enabled} onChange={event=>setMapServers(current=>current.map(item=>item.id===source.id?{...item,enabled:event.target.checked}:item))}/>פעיל</label></article>)}</div></section>
    <section className="v09-panel"><h3>סוגי רכב וטווחי מזהים</h3><div className="v09-vehicle-settings">{draftTypes.map((type,typeIndex)=>{const ranges=normalizeRanges(type.idRanges,type.minId,type.maxId);return <article key={type.id}><header><i style={{background:type.color}}/><input value={type.name} onChange={event=>patchType(type.id,{name:event.target.value})}/><span>צבע קבוע: {typeIndex===0?"כתום":typeIndex===1?"כחול":"סגול"}</span></header><div className="v09-range-list">{ranges.map((range,index)=><div key={index}><label>מ־<input type="number" value={range.min} onChange={event=>setRanges(type.id,ranges.map((item,i)=>i===index?{...item,min:Number(event.target.value)}:item))}/></label><span>עד</span><label><input type="number" value={range.max} onChange={event=>setRanges(type.id,ranges.map((item,i)=>i===index?{...item,max:Number(event.target.value)}:item))}/></label><button aria-label="מחק תחום" onClick={()=>setRanges(type.id,ranges.filter((_,i)=>i!==index))}><Trash2/></button></div>)}</div><button onClick={()=>setRanges(type.id,[...ranges,{min:(ranges.at(-1)?.max??0)+1,max:(ranges.at(-1)?.max??0)+50}])}><Plus/>הוסף תחום</button></article>})}</div></section>
  </div>;
}
