"use client";

import { useMemo, useState } from "react";
import { Download, FileDown, Save, Search } from "lucide-react";
import { toast } from "sonner";

import { relationFromCode, type SoRelation, type SyncTemplate } from "@/lib/bluewolf";
import { useWorkspace } from "../app-context";
import { pointOnClosed, scoreColor } from "./geometry";
import { drawCanvasRoute, fixedVehicleTypes, GROUP_COLORS, TYPE_COLORS } from "./map";
import { getV09Scenario } from "./simulator";
import { siTemplateScores, soTemplateScores } from "./scoring";

type GroupKey = "si" | "so";
type EventRow = { id: string; start: string; end: string; duration: number; group: GroupKey; groupName: string; templateId: string; members: number[]; joined: number[]; left: number[]; total: number; sync: number; route: number; startReason: string; endReason: string; causes: { label: string; timePct: number; impact: number }[] };
type Edit = { templateId: string; note: string };

const clamp = (value: number) => Math.max(0, Math.min(100, Math.round(value)));
const tone = (value: number) => value >= 80 ? "good" : value >= 50 ? "medium" : "low";

function eventRows(serverId: string): EventRow[] {
  const scenario = getV09Scenario(serverId, 150);
  const si = scenario.groups.si; const so = scenario.groups.so;
  return [
    { id: `${serverId}-E1`, start: "17:05", end: "17:34", duration: 29, group: "si", groupName: si.name, templateId: "tpl-si-120", members: si.members.map((m) => m.id).slice(0, 2), joined: si.members.map((m) => m.id).slice(0, 2), left: [], total: 90, sync: 93, route: 82, startReason: `נוצרה קבוצה יציבה: הצטרפו ${si.members.map((m) => m.id).slice(0, 2).join(", ")}`, endReason: si.members[2] ? `רכב ${si.members[2].id} הצטרף והחברות השתנתה` : "שינוי חברות אושר", causes: [{ label: "פער זווית קצר", timePct: 12, impact: 3.1 }, { label: "משיק", timePct: 7, impact: 1.4 }] },
    { id: `${serverId}-E2`, start: "17:34", end: "18:18", duration: 44, group: "si", groupName: si.name, templateId: "tpl-si-120", members: si.members.map((m) => m.id), joined: si.members[2] ? [si.members[2].id] : [], left: [], total: serverId === "3" ? 66 : 94, sync: serverId === "3" ? 58 : 96, route: serverId === "3" ? 90 : 88, startReason: si.members[2] ? `רכב ${si.members[2].id} הצטרף לקבוצה` : "תבנית/קבוצה יציבה אושרה", endReason: `רכב ${si.members[0]?.id ?? 101} יצא מהקבוצה`, causes: serverId === "3" ? [{ label: "שינוי מחזור +22%", timePct: 42, impact: 18.3 }, { label: "אי־התאמת זווית", timePct: 31, impact: 14.8 }] : [{ label: "סטיית זווית", timePct: 6, impact: 1.6 }, { label: "סטיית מחזור", timePct: 4, impact: 1.1 }] },
    { id: `${serverId}-E3`, start: "18:24", end: "19:02", duration: 38, group: "so", groupName: so.name, templateId: "tpl-so-chain", members: so.members.map((m) => m.id), joined: so.members.map((m) => m.id), left: [], total: serverId === "2" ? 72 : 82, sync: serverId === "2" ? 68 : 80, route: serverId === "2" ? 84 : 88, startReason: `SO יציב: הצטרפו ${so.members.map((m) => m.id).join(", ")}`, endReason: so.members[1] ? `רכב ${so.members[1].id} יצא/נותק מעבר ל־hold` : "שינוי גיאומטריה אושר", causes: [{ label: "איחור בפנייה הרחוקה", timePct: 31, impact: 9.5 }, { label: "פער פאזה", timePct: 22, impact: 6.3 }, { label: "סטיית נתיב", timePct: 8, impact: 2.1 }] },
    { id: `${serverId}-E4`, start: "19:02", end: "19:28", duration: 26, group: "so", groupName: so.name, templateId: "tpl-so-chain", members: so.members.map((m) => m.id).filter((_, i) => i !== 1), joined: [], left: so.members[1] ? [so.members[1].id] : [], total: 87, sync: 89, route: 82, startReason: so.members[1] ? `רכב ${so.members[1].id} יצא; הקבוצה החדשה אושרה` : "Membership חדש אושר", endReason: "סיום טווח התחקור", causes: [{ label: "תזמון פנייה", timePct: 10, impact: 2.8 }, { label: "תנועה", timePct: 5, impact: 1.2 }] },
  ];
}

function decodeRelations(template: SyncTemplate | undefined): SoRelation[] { return template?.soSpec?.relations?.length ? template.soSpec.relations : (template?.values ?? []).map(relationFromCode); }

function recalc(event: EventRow, template: SyncTemplate | undefined, state: ReturnType<typeof useWorkspace>["state"]) {
  const scenario = getV09Scenario(event.id.split("-")[0], 150);
  if (event.group === "si") return siTemplateScores(scenario.groups.si.observedAngles ?? [120,120], template?.values ?? [120,120], state.thresholds, state.weights, event.route, scenario.groups.si.periodErrorPct, scenario.groups.si.motionErrorPct);
  return soTemplateScores(scenario.groups.so.observedRelations ?? ["opposite","same"], decodeRelations(template), state.thresholds, state.weights, event.route, scenario.groups.so.periodErrorPct, scenario.groups.so.motionErrorPct);
}

function ReportMap({ serverId, events, selectedId }: { serverId: string; events: EventRow[]; selectedId?: string }) {
  const scenario = getV09Scenario(serverId, 150);
  return <svg className="v09-report-map" viewBox="0 0 1000 570"><defs><pattern id="v09-report-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" /></pattern></defs><rect width="1000" height="570" /><rect width="1000" height="570" fill="url(#v09-report-grid)" />{scenario.routes.map((route, index) => <path key={route.key} d={`M${route.points.map((point) => `${point.x},${point.y}`).join(" L")} Z`} fill="none" stroke={TYPE_COLORS[index % 3]} className="v09-report-route" />)}{events.map((event, index) => { const group = scenario.groups[event.group]; const member = group.members[index % Math.max(1, group.members.length)]; const route = scenario.routes.find((item) => item.key === member?.routeKey) ?? scenario.routes[0]; const p = pointOnClosed(route.points, .13 + index * .18); return <g key={event.id} transform={`translate(${p.x} ${p.y})`} className={selectedId === event.id ? "selected" : ""}><circle r={selectedId === event.id ? 18 : 14} fill={GROUP_COLORS[event.group]} /><text y="5" textAnchor="middle">E{index + 1}</text></g>; })}</svg>;
}

function pdfText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, size = 24, weight = 500, color = "#12313b") { ctx.fillStyle = color; ctx.font = `${weight} ${size}px Arial`; ctx.textAlign = "right"; ctx.direction = "rtl"; ctx.fillText(text, x, y); }
function pageCanvas() { const canvas = document.createElement("canvas"); canvas.width = 1240; canvas.height = 1754; const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("canvas unavailable"); ctx.fillStyle = "#f6fafb"; ctx.fillRect(0,0,canvas.width,canvas.height); return { canvas, ctx }; }

function drawMap(ctx: CanvasRenderingContext2D, serverId: string, x: number, y: number, width: number, height: number, event?: EventRow) {
  const scenario = getV09Scenario(serverId, 150);
  ctx.save(); ctx.fillStyle = "#eaf2f6"; ctx.fillRect(x,y,width,height); ctx.strokeStyle = "rgba(70,100,120,.12)"; ctx.lineWidth = 1;
  for (let gx=x; gx<=x+width; gx+=40) { ctx.beginPath(); ctx.moveTo(gx,y); ctx.lineTo(gx,y+height); ctx.stroke(); }
  for (let gy=y; gy<=y+height; gy+=40) { ctx.beginPath(); ctx.moveTo(x,gy); ctx.lineTo(x+width,gy); ctx.stroke(); }
  ctx.translate(x,y); ctx.scale(width/1000,height/570);
  scenario.routes.forEach((route,index) => drawCanvasRoute(ctx, route.points, TYPE_COLORS[index%3], 5 * 1000 / width));
  if (event) {
    const group = scenario.groups[event.group];
    group.members.forEach((member,index) => { const route = scenario.routes.find((item) => item.key === member.routeKey) ?? scenario.routes[0]; for (let dot=0; dot<10; dot+=1) { const p = pointOnClosed(route.points, member.phase - dot*.025); ctx.fillStyle = GROUP_COLORS[event.group]; ctx.globalAlpha = .25 + dot*.07; ctx.beginPath(); ctx.arc(p.x,p.y,5,0,Math.PI*2); ctx.fill(); } const p = pointOnClosed(route.points, member.phase); ctx.globalAlpha=1; ctx.fillStyle=TYPE_COLORS[index%3]; ctx.beginPath(); ctx.arc(p.x,p.y,8,0,Math.PI*2); ctx.fill(); });
  }
  ctx.restore();
}

function summaryPage(serverId: string, from: string, to: string, events: (EventRow & { effective: ReturnType<typeof recalc> })[], weighted: number) {
  const {canvas,ctx}=pageCanvas(); const gradient=ctx.createLinearGradient(70,70,1170,310); gradient.addColorStop(0,"#071b35");gradient.addColorStop(.6,"#0c7184");gradient.addColorStop(1,"#1cb39f");ctx.fillStyle=gradient;ctx.fillRect(70,70,1100,260);pdfText(ctx,"זאב כחול · דוח תחקור",1110,155,50,800,"#fff");pdfText(ctx,`שרת ${serverId} · ${from.replace("T"," ")} — ${to.replace("T"," ")}`,1110,215,24,500,"#dff7f4");pdfText(ctx,`ציון משוקלל ${weighted} · ${events.length} אירועים`,1110,275,27,700,"#fff");pdfText(ctx,"מפת סיכום כל האירועים",1110,405,30,800);drawMap(ctx,serverId,90,440,1060,520);pdfText(ctx,"אירועים",1110,1030,28,800);events.forEach((event,index)=>{const y=1090+index*135;ctx.fillStyle="#fff";ctx.fillRect(90,y-42,1060,105);pdfText(ctx,`E${index+1} · ${event.groupName}`,1090,y,24,800);pdfText(ctx,`${event.start}–${event.end} · ${event.duration} דק׳`,1090,y+38,19,500,"#69808a");pdfText(ctx,`כולל ${event.effective.total} · Sync ${event.effective.sync} · Route ${event.effective.route}`,600,y+18,20,700,GROUP_COLORS[event.group]);});return canvas;
}

function eventPage(serverId: string, event: EventRow & { effective: ReturnType<typeof recalc> }, index: number) {
  const {canvas,ctx}=pageCanvas();ctx.fillStyle=GROUP_COLORS[event.group];ctx.fillRect(70,70,1100,180);pdfText(ctx,`E${index+1} · ${event.groupName}`,1110,145,44,800,"#fff");pdfText(ctx,`${event.start}–${event.end} · ${event.duration} דקות`,1110,205,23,500,"#f1fbff");const scores=[["כולל",event.effective.total],["Sync",event.effective.sync],["Route",event.effective.route]];scores.forEach(([label,value],i)=>{const x=90+i*350;ctx.fillStyle="#fff";ctx.fillRect(x,300,315,110);pdfText(ctx,String(label),x+270,340,20,500,"#71858d");pdfText(ctx,String(value),x+270,390,36,800);});pdfText(ctx,"מפת האירוע + עקבות",1110,485,28,800);drawMap(ctx,serverId,90,520,1060,480,event);pdfText(ctx,"גבולות האירוע",1110,1060,27,800);pdfText(ctx,`התחלה: ${event.startReason}`,1110,1105,20,600);pdfText(ctx,`סיום: ${event.endReason}`,1110,1142,20,600);pdfText(ctx,`הצטרפו: ${event.joined.length?event.joined.join(", "):"—"} · יצאו: ${event.left.length?event.left.join(", "):"—"}`,1110,1180,20,600,"#536b74");pdfText(ctx,"ציוני רכבים",1110,1250,27,800);event.members.forEach((id,row)=>{const y=1300+row*55;ctx.fillStyle=row%2?"#eef5f7":"#fff";ctx.fillRect(90,y-34,1060,46);pdfText(ctx,`רכב ${id}`,1090,y,19,700);pdfText(ctx,`Total ${clamp(event.effective.total+(row%2?-3:2))} · Sync ${clamp(event.effective.sync+(row%3-1)*3)} · Route ${clamp(event.effective.route+(row%2?2:-2))}`,620,y,18,600,"#617985");});return canvas;
}

function jpegBytes(canvas: HTMLCanvasElement){const base64=canvas.toDataURL("image/jpeg",.92).split(",")[1];const binary=atob(base64);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
function concat(parts: Uint8Array[]){const size=parts.reduce((s,p)=>s+p.length,0);const out=new Uint8Array(size);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}
function buildPdf(canvases: HTMLCanvasElement[]){const enc=new TextEncoder(),images=canvases.map(jpegBytes),count=2+images.length*3,bodies:Uint8Array[]=Array.from({length:count+1},()=>new Uint8Array()),pageIds=images.map((_,i)=>3+i*3);bodies[1]=enc.encode("<< /Type /Catalog /Pages 2 0 R >>");bodies[2]=enc.encode(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${images.length} >>`);images.forEach((image,index)=>{const pageId=3+index*3,contentId=pageId+1,imageId=pageId+2,content=enc.encode("q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n");bodies[pageId]=enc.encode(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);bodies[contentId]=concat([enc.encode(`<< /Length ${content.length} >>\nstream\n`),content,enc.encode("endstream")]);bodies[imageId]=concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`),image,enc.encode("\nendstream")]);});const parts=[enc.encode("%PDF-1.4\n")],offsets=Array(count+1).fill(0);let length=parts[0].length;for(let id=1;id<=count;id++){offsets[id]=length;const obj=concat([enc.encode(`${id} 0 obj\n`),bodies[id],enc.encode("\nendobj\n")]);parts.push(obj);length+=obj.length;}const xrefOffset=length;let xref=`xref\n0 ${count+1}\n0000000000 65535 f \n`;for(let id=1;id<=count;id++)xref+=`${String(offsets[id]).padStart(10,"0")} 00000 n \n`;xref+=`trailer\n<< /Size ${count+1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;parts.push(enc.encode(xref));return concat(parts);}

export function InvestigationViewV09({ server, onServerChange }: { server: string; onServerChange: (server: string) => void }) {
  const { state, save } = useWorkspace();
  const types = useMemo(() => fixedVehicleTypes(state.vehicleTypes), [state.vehicleTypes]);
  const [from,setFrom]=useState("2026-09-05T17:00");const[to,setTo]=useState("2026-09-05T19:30");const[family,setFamily]=useState<"all"|GroupKey>("all");
  const allEvents=useMemo(()=>eventRows(server),[server]);const[selectedId,setSelectedId]=useState(allEvents[1]?.id??allEvents[0]?.id??"");const[edits,setEdits]=useState<Record<string,Edit>>({});
  const selected=allEvents.find(event=>event.id===selectedId)??allEvents[0];const edit=edits[selected.id]??{templateId:selected.templateId,note:""};
  const effective=allEvents.map(event=>{const current=edits[event.id]??{templateId:event.templateId,note:""};const template=state.templates.find(item=>item.id===current.templateId)??state.templates.find(item=>item.id===event.templateId);return{...event,effective:recalc(event,template,state),note:current.note,template};});
  const filtered=effective.filter(event=>family==="all"||event.group===family);const totalMinutes=effective.reduce((sum,event)=>sum+event.duration,0);const weighted=Math.round(effective.reduce((sum,event)=>sum+event.effective.total*event.duration,0)/Math.max(1,totalMinutes));const best=[...effective].sort((a,b)=>b.effective.total-a.effective.total)[0];
  const currentEffective=effective.find(event=>event.id===selected.id)??effective[0];
  const rootMap=new Map<string,{time:number;impact:number}>();effective.forEach(event=>event.causes.forEach(cause=>{const current=rootMap.get(cause.label)??{time:0,impact:0};current.time+=cause.timePct*event.duration;current.impact+=cause.impact;rootMap.set(cause.label,current);}));const roots=[...rootMap.entries()].sort((a,b)=>b[1].impact-a[1].impact).slice(0,5);
  const exportPdf=()=>{try{const canvases=[summaryPage(server,from,to,effective,weighted),...effective.map((event,index)=>eventPage(server,event,index))];const pdf=buildPdf(canvases);const blob=new Blob([pdf],{type:"application/pdf"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`Blue-Wolf-${server}-${from.slice(0,10)}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success("PDF נוצר עם מפת סיכום ומפה לכל Event");}catch(error){toast.error(error instanceof Error?error.message:"PDF failed");}};
  const saveEdit=async()=>{await save({...state,vehicleTypes:types,investigationEdits:{...state.investigationEdits,[selected.id]:{note:edit.note,templateId:edit.templateId}}},"investigation","edit-v09",selected.id);toast.success("השינוי נשמר");};

  return <div className="v09-investigation"><header className="v09-page-head"><div><p className="eyebrow">AFTER ACTION · SRS v1.1</p><h1>תחקור לאחור</h1><p>אירועים לפי זהות קבוצה יציבה. גבולות מציינים במפורש מי הצטרף ומי יצא.</p></div><div className="v09-actions"><button onClick={()=>toast.success("הטווח נטען") }><Search/>טען</button><button className="primary" onClick={exportPdf}><FileDown/>PDF עם מפות</button></div></header>
    <section className="v09-panel v09-report-filter"><label>שרת<select value={server} onChange={event=>{onServerChange(event.target.value);setSelectedId(`${event.target.value}-E2`);}}>{state.servers.filter(item=>item.enabled).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>מתאריך<input type="datetime-local" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>עד תאריך<input type="datetime-local" value={to} onChange={event=>setTo(event.target.value)}/></label><label>משפחה<select value={family} onChange={event=>setFamily(event.target.value as "all"|GroupKey)}><option value="all">הכול</option><option value="si">SI</option><option value="so">SO</option></select></label></section>
    <div className="v09-kpis"><article><span>ציון משוקלל בזמן</span><b className={tone(weighted)}>{weighted}</b><small>{totalMinutes} דקות</small></article><article><span>אירועים</span><b>{effective.length}</b><small>Alert לא נספר כאירוע</small></article><article><span>Best Event</span><b>{best.effective.total}</b><small>{best.start}–{best.end}</small></article><article><span>קבוצות</span><b>2</b><small>SI + SO</small></article><article><span>מפות PDF</span><b>✓</b><small>Summary + per Event</small></article></div>
    <div className="v09-report-grid"><main><section className="v09-panel"><div className="v09-panel-head"><div><h2>מפת סיכום</h2><p>מיקום יחסי אמיתי, נתיבים בצבע סוג רכב, Event בצבע קבוצה.</p></div><button onClick={()=>{const payload={server,from,to,weighted,events:effective};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="bluewolf-report.json";a.click();URL.revokeObjectURL(url);}}><Download/>JSON</button></div><ReportMap serverId={server} events={allEvents} selectedId={selected.id}/></section>
      <section className="v09-event-list">{filtered.map((event,index)=><button key={event.id} className={`v09-event-card ${event.id===selected.id?"active":""}`} onClick={()=>setSelectedId(event.id)}><span className="v09-event-color" style={{background:GROUP_COLORS[event.group]}}/><div><p className="eyebrow">E{allEvents.findIndex(item=>item.id===event.id)+1} · {event.start}–{event.end}</p><h3>{event.groupName}</h3><p>הצטרפו: {event.joined.length?event.joined.join(", "):"—"} · יצאו: {event.left.length?event.left.join(", "):"—"}</p></div><strong className={tone(event.effective.total)}>{event.effective.total}</strong></button>)}</section>
      {currentEffective&&<section className="v09-panel v09-event-detail"><div className="v09-panel-head"><div><p className="eyebrow">{currentEffective.id}</p><h2>{currentEffective.groupName}</h2><p>{currentEffective.start}–{currentEffective.end} · {currentEffective.duration} דק׳</p></div><div className="v09-score-badges"><span>כולל <b>{currentEffective.effective.total}</b></span><span>Sync <b>{currentEffective.effective.sync}</b></span><span>Route <b>{currentEffective.effective.route}</b></span></div></div><ReportMap serverId={server} events={[selected]} selectedId={selected.id}/><div className="v09-boundaries"><article><b>התחלה</b><p>{selected.startReason}</p><span>הצטרפו: {selected.joined.length?selected.joined.join(", "):"—"}</span></article><article><b>סיום</b><p>{selected.endReason}</p><span>יצאו: {selected.left.length?selected.left.join(", "):"—"}</span></article></div><div className="v09-member-table"><div className="head"><span>רכב</span><span>כולל</span><span>Sync</span><span>Route</span><span>מצב</span></div>{selected.members.map((id,index)=><div key={id}><span>רכב {id}</span><span>{clamp(currentEffective.effective.total+(index%2?-3:2))}</span><span>{clamp(currentEffective.effective.sync+(index%3-1)*3)}</span><span>{clamp(currentEffective.effective.route+(index%2?2:-2))}</span><span>{index===selected.members.length-1&&selected.left.includes(id)?"יצא":"פעיל"}</span></div>)}</div><div className="v09-report-edit"><label>Template override<select value={edit.templateId} onChange={event=>setEdits(current=>({...current,[selected.id]:{...edit,templateId:event.target.value}}))}>{state.templates.filter(template=>template.family===(selected.group==="si"?"SI":"SO")).map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label>הערת תחקור<textarea value={edit.note} onChange={event=>setEdits(current=>({...current,[selected.id]:{...edit,note:event.target.value}}))}/></label><div className="v09-recalc-note">חישוב מיידי לפני שמירה: <b>{currentEffective.effective.total}</b></div><button className="primary" onClick={saveEdit}><Save/>שמור</button></div></section>}
    </main><aside><section className="v09-panel"><p className="eyebrow">BEST EVENT</p><h3>{best.groupName}</h3><b className={`v09-big-score ${tone(best.effective.total)}`}>{best.effective.total}</b><p>{best.start}–{best.end}</p></section><section className="v09-panel"><h3>גורמי שורש מרכזיים</h3>{roots.map(([label,value])=><div key={label} className="v09-root"><div><span>{label}</span><b>−{value.impact.toFixed(1)}</b></div><i><em style={{width:`${Math.min(100,value.impact*4)}%`}}/></i></div>)}</section></aside></div>
  </div>;
}
