"use client";

import { useMemo, useRef, useState } from "react";
import { Link2, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";

import { createId, type SavedRoute } from "@/lib/bluewolf";
import { useWorkspace } from "../app-context";
import { doubleHippodromeLoop, figureEightLoop, hippodromeLoop, svgClosedPath, type Point } from "./geometry";
import { fixedVehicleTypes } from "./map";

type Params = { radius: number; legLength: number; rotationDeg: number; secondLegLength?: number; bendDeg?: number; doubleSourceIds?: string[] };
type DragHandle = { routeId: string; kind: "center"|"radius"|"leg"|"angle"|"leg2" };

const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const angle=(a:Point,b:Point)=>Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;
const unit=(deg:number)=>({x:Math.cos(deg*Math.PI/180),y:Math.sin(deg*Math.PI/180)});

function parseParams(route: SavedRoute): Params {
  try { const raw=JSON.parse(route.geometry) as Partial<Params>&{v09?:boolean}; if(raw.v09)return{radius:raw.radius??32,legLength:route.family==="SI"?0:raw.legLength??110,rotationDeg:raw.rotationDeg??route.rotationDeg??0,secondLegLength:raw.secondLegLength,bendDeg:raw.bendDeg,doubleSourceIds:raw.doubleSourceIds}; } catch {}
  return {radius:route.family==="SI"?42:30,legLength:route.family==="SI"?0:route.routeKind==="double"?105:110,rotationDeg:route.rotationDeg??0,secondLegLength:route.routeKind==="double"?100:undefined,bendDeg:route.routeKind==="double"?28:undefined};
}
function encodeParams(params: Params){return JSON.stringify({v09:true,...params});}
function center(route:SavedRoute):Point{return{x:(route.mapX??50)/100*900,y:(route.mapY??50)/100*460};}
function kind(route:SavedRoute):"circle"|"single"|"double"|"figure8"{if(route.family==="SI")return"circle";if(route.routeKind==="double")return"double";if(route.routeKind==="figure8")return"figure8";return"single";}
function pointsFor(route:SavedRoute){const p=parseParams(route),c=center(route),k=kind(route);if(k==="circle")return hippodromeLoop(c,p.radius,0,p.rotationDeg);if(k==="figure8")return figureEightLoop(c,p.radius,p.legLength,p.rotationDeg);if(k==="double")return doubleHippodromeLoop(c,p.radius,p.legLength,p.secondLegLength??p.legLength,p.bendDeg??28,p.rotationDeg);return hippodromeLoop(c,p.radius,p.legLength,p.rotationDeg);}

export function V09RouteBank(){
  const{state,save}=useWorkspace();const types=useMemo(()=>fixedVehicleTypes(state.vehicleTypes),[state.vehicleTypes]);const[routes,setRoutes]=useState<SavedRoute[]>(structuredClone(state.routes));const[selectedId,setSelectedId]=useState<string|null>(routes[0]?.id??null);const[connectIds,setConnectIds]=useState<string[]>([]);const[drag,setDrag]=useState<DragHandle|null>(null);const svgRef=useRef<SVGSVGElement|null>(null);const selected=routes.find(route=>route.id===selectedId)??null;const params=selected?parseParams(selected):null;
  const patch=(id:string,patch:Partial<SavedRoute>)=>setRoutes(current=>current.map(route=>route.id===id?{...route,...patch,updatedAt:new Date().toISOString()}:route));
  const patchParams=(route:SavedRoute,next:Partial<Params>)=>{const current=parseParams(route),merged={...current,...next};patch(route.id,{geometry:encodeParams(merged),rotationDeg:merged.rotationDeg});};
  const svgPoint=(event:React.PointerEvent)=>{const rect=svgRef.current?.getBoundingClientRect();if(!rect)return{x:0,y:0};return{x:(event.clientX-rect.left)/Math.max(1,rect.width)*900,y:(event.clientY-rect.top)/Math.max(1,rect.height)*460};};
  const moveHandle=(event:React.PointerEvent)=>{if(!drag)return;const route=routes.find(item=>item.id===drag.routeId);if(!route)return;const p=svgPoint(event),c=center(route),pr=parseParams(route),u=unit(pr.rotationDeg),n={x:-u.y,y:u.x};if(drag.kind==="center"){patch(route.id,{mapX:clamp(p.x/9,2,98),mapY:clamp(p.y/4.6,3,97)});return;}if(drag.kind==="angle"){patchParams(route,{rotationDeg:angle(c,p)});return;}if(drag.kind==="radius"){const dx=p.x-c.x,dy=p.y-c.y;patchParams(route,{radius:clamp(Math.abs(dx*n.x+dy*n.y),10,95)});return;}if(drag.kind==="leg"){const dx=p.x-c.x,dy=p.y-c.y;patchParams(route,{legLength:route.family==="SI"?0:clamp(Math.abs(dx*u.x+dy*u.y)*2,20,300)});return;}if(drag.kind==="leg2"){const dx=p.x-c.x,dy=p.y-c.y;patchParams(route,{secondLegLength:clamp(Math.hypot(dx,dy),20,300),bendDeg:clamp(angle(c,p)-pr.rotationDeg,-100,100)});}};
  const addRoute=()=>{const route:SavedRoute={id:createId("route"),name:"נתיב חדש",arena:state.arenas[0]??"Arena",vehicleType:types[0]?.name??"סוג א׳",family:"SO",geometry:encodeParams({radius:30,legLength:110,rotationDeg:0}),updatedAt:new Date().toISOString(),routeKind:"single",mapX:50,mapY:50,rotationDeg:0,scalePct:100};setRoutes(current=>[...current,route]);setSelectedId(route.id);};
  const convert=(target:"circle"|"single"|"figure8")=>{if(!selected)return;const current=parseParams(selected);if(target==="circle")patch(selected.id,{family:"SI",routeKind:"compact",geometry:encodeParams({...current,legLength:0})});if(target==="single")patch(selected.id,{family:"SO",routeKind:"single",geometry:encodeParams({...current,legLength:Math.max(70,current.legLength||0)})});if(target==="figure8")patch(selected.id,{family:"SO",routeKind:"figure8",geometry:encodeParams({...current,legLength:Math.max(70,current.legLength||0)})});};
  const connectDouble=()=>{if(connectIds.length!==2){toast.error("בחר בדיוק שני היפודרומים לחיבור");return;}const a=routes.find(route=>route.id===connectIds[0]),b=routes.find(route=>route.id===connectIds[1]);if(!a||!b){return;}const ca=center(a),cb=center(b),pa=parseParams(a),pb=parseParams(b),mid={x:(ca.x+cb.x)/2,y:(ca.y+cb.y)/2},rot=angle(ca,cb),bend=clamp(pb.rotationDeg-pa.rotationDeg,-75,75);const route:SavedRoute={id:createId("double"),name:`Double · ${a.name} + ${b.name}`,arena:a.arena,vehicleType:a.vehicleType,family:"SO",routeKind:"double",geometry:encodeParams({radius:(pa.radius+pb.radius)/2,legLength:Math.max(45,Math.hypot(mid.x-ca.x,mid.y-ca.y)+pa.legLength/2),secondLegLength:Math.max(45,Math.hypot(cb.x-mid.x,cb.y-mid.y)+pb.legLength/2),rotationDeg:rot,bendDeg:bend||28,doubleSourceIds:[a.id,b.id]}),updatedAt:new Date().toISOString(),mapX:mid.x/9,mapY:mid.y/4.6,rotationDeg:rot,scalePct:100};setRoutes(current=>[...current,route]);setSelectedId(route.id);setConnectIds([]);toast.success("נוצר Double רציף משני ההיפודרומים שסומנו");};
  return <div><header className="v09-section-header"><div><p className="eyebrow">ROUTE BANK · PARAMETRIC EDITOR</p><h2>בנק נתיבים</h2><p>אותו עורך למעגל ולהיפודרום: מרכז, רדיוס, זווית ואורך Leg. Double נוצר מחיבור שני היפודרומים שסימנת.</p></div><div className="v09-actions"><button onClick={addRoute}><Plus/>נתיב</button><button disabled={connectIds.length!==2} onClick={connectDouble}><Link2/>חבר 2 ל‑Double</button><button className="primary" onClick={async()=>{await save({...state,vehicleTypes:types,routes},"routes","save-v09",`${routes.length}`);toast.success("בנק הנתיבים נשמר")}}><Save/>שמור</button></div></header>
    <section className="v09-route-workspace"><div className="v09-panel"><svg ref={svgRef} className="v09-route-map" viewBox="0 0 900 460" onPointerMove={moveHandle} onPointerUp={()=>setDrag(null)} onPointerLeave={()=>setDrag(null)}><defs><pattern id="v09-route-grid" width="36" height="36" patternUnits="userSpaceOnUse"><path d="M36 0H0V36"/></pattern></defs><rect width="900" height="460"/><rect width="900" height="460" fill="url(#v09-route-grid)"/><g className="v09-route-context"><path d="M-20 400C180 300 300 430 460 322S700 215 930 270"/><path d="M40 90C200 140 350 110 500 65S730 45 870 105"/></g>{routes.map(route=>{const pts=pointsFor(route),type=types.find(item=>item.name===route.vehicleType),color=type?.color??"#8a9aa5",sel=route.id===selectedId,c=center(route),p=parseParams(route),u=unit(p.rotationDeg),n={x:-u.y,y:u.x},radiusH={x:c.x+n.x*p.radius,y:c.y+n.y*p.radius},legH={x:c.x+u.x*p.legLength/2,y:c.y+u.y*p.legLength/2},angleH={x:c.x+u.x*(Math.max(40,p.legLength/2)+p.radius+38),y:c.y+u.y*(Math.max(40,p.legLength/2)+p.radius+38)},leg2Angle=(p.rotationDeg+(p.bendDeg??28)),u2=unit(leg2Angle),leg2H={x:c.x+u2.x*(p.secondLegLength??p.legLength),y:c.y+u2.y*(p.secondLegLength??p.legLength)};return <g key={route.id} className={sel?"selected":""} onClick={()=>setSelectedId(route.id)}><path d={svgClosedPath(pts)} fill="none" stroke={color} className="v09-route-shape"/><text x={c.x} y={c.y+p.radius+58} textAnchor="middle" className="v09-route-name">{route.name}</text>{sel&&<g className="v09-param-handles"><line x1={c.x} y1={c.y} x2={radiusH.x} y2={radiusH.y}/><line x1={c.x} y1={c.y} x2={legH.x} y2={legH.y}/><line x1={c.x} y1={c.y} x2={angleH.x} y2={angleH.y}/><circle cx={c.x} cy={c.y} r="9" data-kind="center" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);setDrag({routeId:route.id,kind:"center"})}}/><circle cx={radiusH.x} cy={radiusH.y} r="8" data-kind="radius" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);setDrag({routeId:route.id,kind:"radius"})}}/>{route.family!=="SI"&&<circle cx={legH.x} cy={legH.y} r="8" data-kind="leg" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);setDrag({routeId:route.id,kind:"leg"})}}/>}<circle cx={angleH.x} cy={angleH.y} r="8" data-kind="angle" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);setDrag({routeId:route.id,kind:"angle"})}}/>{route.routeKind==="double"&&<><line x1={c.x} y1={c.y} x2={leg2H.x} y2={leg2H.y}/><circle cx={leg2H.x} cy={leg2H.y} r="8" data-kind="leg2" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);setDrag({routeId:route.id,kind:"leg2"})}}/></>}<text x={c.x+12} y={c.y-12}>מרכז</text><text x={radiusH.x+10} y={radiusH.y-8}>רדיוס</text>{route.family!=="SI"&&<text x={legH.x+10} y={legH.y-8}>אורך</text>}<text x={angleH.x+10} y={angleH.y-8}>זווית</text></g>}</g>})}</svg></div>
      <aside className="v09-panel v09-route-editor">{selected&&params?<><p className="eyebrow">עריכת נתיב</p><label>שם<input value={selected.name} onChange={event=>patch(selected.id,{name:event.target.value})}/></label><label>סוג רכב<select value={selected.vehicleType} onChange={event=>patch(selected.id,{vehicleType:event.target.value})}>{types.map(type=><option key={type.id}>{type.name}</option>)}</select></label><label>Arena · metadata<select value={selected.arena} onChange={event=>patch(selected.id,{arena:event.target.value})}>{state.arenas.map(arena=><option key={arena}>{arena}</option>)}</select></label><div className="v09-route-kind-buttons"><button className={kind(selected)==="circle"?"active":""} onClick={()=>convert("circle")}>מעגל · Leg 0</button><button className={kind(selected)==="single"?"active":""} onClick={()=>convert("single")}>היפודרום</button><button className={kind(selected)==="figure8"?"active":""} onClick={()=>convert("figure8")}>הפוך לשמינייה</button></div><dl className="v09-param-values"><div><dt>רדיוס</dt><dd>{Math.round(params.radius)}</dd></div><div><dt>Leg</dt><dd>{Math.round(params.legLength)}</dd></div><div><dt>זווית</dt><dd>{Math.round(params.rotationDeg)}°</dd></div>{selected.routeKind==="double"&&<div><dt>Leg 2</dt><dd>{Math.round(params.secondLegLength??params.legLength)}</dd></div>}</dl><p className="v09-help-text">גרור את צירי המרכז/רדיוס/אורך/זווית על המפה. במעגל Leg נשאר 0. הכפתור “שמינייה” מחליף את התוואי לתוואי מוצלב.</p><button className="danger" onClick={()=>{setRoutes(current=>current.filter(route=>route.id!==selected.id));setSelectedId(null);}}><Trash2/>מחק</button></>:<p>בחר נתיב</p>}</aside></section>
    <section className="v09-panel"><div className="v09-panel-head"><div><h3>בחירת שני היפודרומים לחיבור</h3><p>צייר/ערוך כל היפודרום בנפרד, סמן בדיוק שניים ולחץ “חבר 2 ל‑Double”.</p></div><b>{connectIds.length}/2</b></div><div className="v09-route-list">{routes.filter(route=>route.family==="SO"&&route.routeKind!=="double").map(route=><label key={route.id} className={connectIds.includes(route.id)?"active":""}><input type="checkbox" checked={connectIds.includes(route.id)} onChange={event=>setConnectIds(current=>event.target.checked?[...current.filter(id=>id!==route.id),route.id].slice(-2):current.filter(id=>id!==route.id))}/><i style={{background:types.find(type=>type.name===route.vehicleType)?.color}}/><span><b>{route.name}</b><small>{route.vehicleType} · {kind(route)}</small></span></label>)}</div></section>
  </div>;
}
