"""Public contract for the Blue Wolf algorithmic core.

Only symbols imported here are considered part of the stable envelope used by
the surrounding application. The package intentionally has no knowledge of
InfluxDB, SQLite, HTTP, maps, reports, or display time zones.
"""

from .config import CoreConfig
from .geometry import (
    PolylineProjection,
    circular_phase_distance,
    closed_polyline_length,
    curvature_at_phase,
    normalized_curvature_error,
    point_at_phase,
    project_onto_closed_polyline,
    project_wgs84,
    resample_closed_polyline,
    tangent_error_deg,
)
from .models import (
    ChangeKind,
    ClosedRoute,
    CoreBatchResult,
    Direction,
    FieldQuality,
    PrimitiveMetrics,
    RouteFamily,
    RouteSubtype,
    RouteTopology,
    StateChange,
    VehicleFrameResult,
    VehicleSample,
    VehicleScores,
)
from .route_detection import RouteDetection, detect_closed_route
from .scoring import aggregate_group_scores, score_error, score_vehicle
from .session import CheckpointCompatibilityError, CoreSession
from .templates import (
    MemberTemplateFit,
    NoLegalTemplateAssignment,
    ObservedMember,
    SynchronizationTemplate,
    TemplateFit,
    TemplateSlot,
    fit_template,
)
from .v08_core import (
    GroupLifecycleEvent,
    LifecycleEvent,
    Point2D,
    Rotation,
    RouteDescriptor,
    RouteKind,
    RouteLifecycle,
    RouteShape,
    SoEntity,
    SoEntityKind,
    SoLayout,
    SoRelation,
    StableGroupLifecycle,
    angle_delta_deg,
    canonical_so_layout_key,
    classify_route,
    grouping_compatible,
    material_change,
    relative_period_error,
    si_group_compatible,
    so_group_compatible,
    validate_so_layout,
)
from .sync_v08 import (
    DoubleSingleEquivalent,
    circular_angle_distance_deg,
    circular_cycle_distance,
    double_as_single,
    double_quarter,
    double_quarter_relation,
    phase_in_region,
    si_pair_angle_error_deg,
    si_tangent_error_deg,
    so_relation_phase_error,
    so_turn_weighted_error,
)

RouteLifecycleV08 = RouteLifecycle

__all__ = [
    "ChangeKind",
    "CheckpointCompatibilityError",
    "ClosedRoute",
    "CoreBatchResult",
    "CoreConfig",
    "CoreSession",
    "Direction",
    "DoubleSingleEquivalent",
    "FieldQuality",
    "GroupLifecycleEvent",
    "LifecycleEvent",
    "MemberTemplateFit",
    "NoLegalTemplateAssignment",
    "ObservedMember",
    "Point2D",
    "PrimitiveMetrics",
    "PolylineProjection",
    "Rotation",
    "RouteDescriptor",
    "RouteDetection",
    "RouteFamily",
    "RouteKind",
    "RouteLifecycle",
    "RouteLifecycleV08",
    "RouteShape",
    "RouteSubtype",
    "RouteTopology",
    "SoEntity",
    "SoEntityKind",
    "SoLayout",
    "SoRelation",
    "StableGroupLifecycle",
    "StateChange",
    "SynchronizationTemplate",
    "TemplateFit",
    "TemplateSlot",
    "VehicleFrameResult",
    "VehicleSample",
    "VehicleScores",
    "aggregate_group_scores",
    "angle_delta_deg",
    "canonical_so_layout_key",
    "circular_angle_distance_deg",
    "circular_cycle_distance",
    "circular_phase_distance",
    "classify_route",
    "closed_polyline_length",
    "curvature_at_phase",
    "detect_closed_route",
    "double_as_single",
    "double_quarter",
    "double_quarter_relation",
    "fit_template",
    "grouping_compatible",
    "material_change",
    "normalized_curvature_error",
    "phase_in_region",
    "point_at_phase",
    "project_onto_closed_polyline",
    "project_wgs84",
    "relative_period_error",
    "resample_closed_polyline",
    "score_error",
    "score_vehicle",
    "si_group_compatible",
    "si_pair_angle_error_deg",
    "si_tangent_error_deg",
    "so_group_compatible",
    "so_relation_phase_error",
    "so_turn_weighted_error",
    "tangent_error_deg",
    "validate_so_layout",
]

__version__ = "0.8.0"
